Repository prgrms-web-devcourse-final-project/WEB1_1_Bongdari_BE, pull requests merged in 2024-12, with the labels that each got.

#77 Feature/76 커뮤니티 댓글 수정 기능
  src/main/java/com/somemore/community/domain/CommunityComment.java
  src/main/java/com/somemore/community/dto/request/CommunityCommentUpdateRequestDto.java
  src/main/java/com/somemore/community/service/comment/UpdateCommunityCommentService.java
  src/main/java/com/somemore/community/usecase/comment/UpdateCommunityCommentUseCase.java
  src/test/java/com/somemore/community/service/comment/UpdateCommunityCommentServiceTest.java
Labels: Feature, 아영

#95 Feature/63 봉사자 조회, 상세 조회, 검증
  build.gradle
  src/main/java/com/somemore/auth/cookie/CookieService.java
  src/main/java/com/somemore/auth/jwt/domain/UserRole.java
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/auth/jwt/filter/UserRole.java
  src/main/java/com/somemore/auth/jwt/generator/HmacJwtGenerator.java
  src/main/java/com/somemore/auth/jwt/service/GenerateTokensOnLoginService.java
  src/main/java/com/somemore/auth/oauth/handler/success/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/auth/util/DevAccountSetUpConfig.java
  src/main/java/com/somemore/domains/VolunteerManagement.java
  src/main/java/com/somemore/facade/validator/VolunteerDetailAccessValidator.java
  src/main/java/com/somemore/facade/validator/VolunteerDetailAccessValidatorImpl.java
  src/main/java/com/somemore/global/configure/SecurityConfig.java
  src/main/java/com/somemore/global/exception/BadRequestException.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepository.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/main/java/com/somemore/recruitboard/service/query/RecruitBoardQueryService.java
  src/main/java/com/somemore/recruitboard/usecase/query/RecruitBoardQueryUseCase.java
  src/main/java/com/somemore/volunteer/controller/VolunteerQueryController.java
  src/main/java/com/somemore/volunteer/domain/VolunteerDetail.java
  src/main/java/com/somemore/volunteer/dto/response/VolunteerResponseDto.java
  src/main/java/com/somemore/volunteer/repository/VolunteerDetailJpaRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerDetailRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerDetailRepositoryImpl.java
  src/main/java/com/somemore/volunteer/repository/VolunteerJpaRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepositoryImpl.java
  src/main/java/com/somemore/volunteer/service/FindVolunteerIdService.java
  src/main/java/com/somemore/volunteer/service/VolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/FindVolunteerIdUseCase.java
  src/main/java/com/somemore/volunteer/usecase/VolunteerQueryUseCase.java
  src/main/java/com/somemore/volunteerapply/domain/ApplyStatus.java
  src/main/java/com/somemore/volunteerapply/domain/VolunteerApply.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyJpaRepository.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepository.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImpl.java
  src/main/java/com/somemore/volunteerapply/service/VolunteerApplyQueryService.java
  src/main/java/com/somemore/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
  src/test/java/com/somemore/ControllerTestSupport.java
  src/test/java/com/somemore/IntegrationTestSupport.java
  src/test/java/com/somemore/auth/jwt/service/JwtServiceTest.java
  src/test/java/com/somemore/center/controller/CenterQueryApiControllerTest.java
  src/test/java/com/somemore/common/fixture/RecruitBoardFixture.java
  src/test/java/com/somemore/facade/validator/VolunteerDetailAccessValidatorImplTest.java
  src/test/java/com/somemore/interestcenter/service/RegisterInterestCenterServiceTest.java
  src/test/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImplTest.java
  src/test/java/com/somemore/recruitboard/service/query/RecruitBoardQueryServiceTest.java
  src/test/java/com/somemore/volunteer/controller/VolunteerSignControllerTest.java
  src/test/java/com/somemore/volunteer/repository/VolunteerDetailRepositoryImplTest.java
  src/test/java/com/somemore/volunteer/repository/VolunteerRepositoryTest.java
  src/test/java/com/somemore/volunteer/service/FindVolunteerIdServiceTest.java
  src/test/java/com/somemore/volunteer/service/RegisterVolunteerServiceTest.java
  src/test/java/com/somemore/volunteer/service/SignOutVolunteerServiceTest.java
  src/test/java/com/somemore/volunteer/service/VolunteerQueryServiceTest.java
  src/test/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImplTest.java
  src/test/java/com/somemore/volunteerapply/service/VolunteerApplyQueryServiceTest.java
Labels: Feature, 재중

#106 Feature/97 봉사자 프로필 수정
  build.gradle
  src/main/java/com/somemore/global/handler/GlobalExceptionHandler.java
  src/main/java/com/somemore/volunteer/controller/VolunteerProfileCommandController.java
  src/main/java/com/somemore/volunteer/controller/VolunteerProfileQueryController.java
  src/main/java/com/somemore/volunteer/domain/Volunteer.java
  src/main/java/com/somemore/volunteer/dto/request/VolunteerProfileUpdateRequestDto.java
  src/main/java/com/somemore/volunteer/dto/response/VolunteerProfileResponseDto.java
  src/main/java/com/somemore/volunteer/service/UpdateVolunteerProfileService.java
  src/main/java/com/somemore/volunteer/service/VolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/UpdateVolunteerProfileUseCase.java
  src/main/java/com/somemore/volunteer/usecase/VolunteerQueryUseCase.java
  src/test/java/com/somemore/volunteer/controller/VolunteerProfileCommandControllerTest.java
  src/test/java/com/somemore/volunteer/service/UpdateVolunteerProfileServiceTest.java
  src/test/java/com/somemore/volunteer/service/VolunteerQueryServiceTest.java
Labels: Feature, 재중

#102 Feature/79 리뷰 등록
  src/main/java/com/somemore/domains/Review.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/global/handler/GlobalExceptionHandler.java
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiController.java
  src/main/java/com/somemore/review/controller/ReviewCommandApiController.java
  src/main/java/com/somemore/review/domain/Review.java
  src/main/java/com/somemore/review/dto/request/ReviewCreateRequestDto.java
  src/main/java/com/somemore/review/repository/ReviewJpaRepository.java
  src/main/java/com/somemore/review/repository/ReviewRepository.java
  src/main/java/com/somemore/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/somemore/review/service/CreateReviewService.java
  src/main/java/com/somemore/review/usecase/CreateReviewUseCase.java
  src/main/java/com/somemore/volunteerapply/domain/VolunteerApply.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepository.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImpl.java
  src/main/java/com/somemore/volunteerapply/service/VolunteerApplyQueryService.java
  src/main/java/com/somemore/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
  src/test/java/com/somemore/review/controller/ReviewCommandApiControllerTest.java
  src/test/java/com/somemore/review/repository/ReviewRepositoryImplTest.java
  src/test/java/com/somemore/review/service/CreateReviewServiceTest.java
  src/test/java/com/somemore/volunteerapply/domain/VolunteerApplyTest.java
  src/test/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImplTest.java
  src/test/java/com/somemore/volunteerapply/service/VolunteerApplyQueryServiceTest.java
Labels: Feature, 범수

#109 Feature/104 기관 로그인
  src/main/java/com/somemore/auth/authentication/JwtAuthenticationToken.java
  src/main/java/com/somemore/auth/idpw/filter/IdPwAuthFilter.java
  src/main/java/com/somemore/auth/idpw/provider/CustomAuthenticationProvider.java
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/somemore/auth/jwt/service/GenerateTokensOnLoginService.java
  src/main/java/com/somemore/auth/jwt/usecase/GenerateTokensOnLoginUseCase.java
  src/main/java/com/somemore/auth/oauth/handler/success/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/center/repository/CenterJpaRepository.java
  src/main/java/com/somemore/center/repository/CenterRepository.java
  src/main/java/com/somemore/center/repository/CenterRepositoryImpl.java
  src/main/java/com/somemore/center/service/query/CenterSignService.java
  src/main/java/com/somemore/center/usecase/query/CenterSignUseCase.java
  src/main/java/com/somemore/global/configure/SecurityConfig.java
  src/main/java/com/somemore/volunteer/controller/VolunteerSignController.java
  src/test/java/com/somemore/center/repository/CenterRepositoryTest.java
  src/test/java/com/somemore/center/service/query/CenterSignServiceTest.java
Labels: Feature, 재중

#108 Feature/78 커뮤니티 댓글 조회 기능
  src/main/java/com/somemore/community/domain/CommunityComment.java
  src/main/java/com/somemore/community/dto/response/CommunityBoardGetResponseDto.java
  src/main/java/com/somemore/community/dto/response/CommunityCommentResponseDto.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepository.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/community/repository/comment/CommunityCommentRepository.java
  src/main/java/com/somemore/community/repository/comment/CommunityCommentRepositoryImpl.java
  src/main/java/com/somemore/community/repository/mapper/CommunityBoardView.java
  src/main/java/com/somemore/community/repository/mapper/CommunityCommentView.java
  src/main/java/com/somemore/community/service/board/CommunityBoardQueryService.java
  src/main/java/com/somemore/community/service/comment/CommunityCommentQueryService.java
  src/main/java/com/somemore/community/usecase/comment/CommunityCommentQueryUseCase.java
  src/test/java/com/somemore/community/repository/CommunityBoardRepositoryTest.java
  src/test/java/com/somemore/community/repository/CommunityCommentRepositoryTest.java
  src/test/java/com/somemore/community/service/comment/CommunityCommentQueryServiceTest.java
Labels: Feature, 아영

#114 Feature/111 CORS
  src/main/java/com/somemore/global/configure/SecurityConfig.java
  src/main/java/com/somemore/global/configure/WebConfig.java
Labels: Feature, 재중

#112 Feature/107 선호물품 등록 엔드포인트 구현
  src/main/java/com/somemore/center/controller/PreferItemCommandApiController.java
  src/main/java/com/somemore/center/dto/request/PreferItemCreateRequestDto.java
  src/main/java/com/somemore/center/dto/response/PreferItemCreateResponseDto.java
  src/main/java/com/somemore/center/service/command/CreatePreferItemService.java
  src/main/java/com/somemore/center/usecase/command/CreatePreferItemUseCase.java
  src/test/java/com/somemore/center/controller/PreferItemCommandApiControllerTest.java
  src/test/java/com/somemore/center/service/command/CreatePreferItemServiceTest.java
Labels: Feature, 서진

#115 Feature/110 기관 로그아웃
  src/main/java/com/somemore/auth/oauth/handler/failure/CustomOAuthFailureHandler.java
  src/main/java/com/somemore/auth/signout/service/SignOutService.java
  src/main/java/com/somemore/auth/signout/usecase/SignOutUseCase.java
  src/main/java/com/somemore/center/controller/CenterSignController.java
  src/main/java/com/somemore/global/configure/WebConfig.java
  src/main/java/com/somemore/volunteer/controller/VolunteerSignController.java
  src/test/java/com/somemore/volunteer/service/SignOutVolunteerServiceTest.java
Labels: Feature, 재중

#116 Feature/99 리뷰 조회 기능
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardQueryApiController.java
  src/main/java/com/somemore/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/recruitboard/domain/RecruitmentInfo.java
  src/main/java/com/somemore/recruitboard/domain/VolunteerCategory.java
  src/main/java/com/somemore/recruitboard/dto/condition/RecruitBoardSearchCondition.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardDetailResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithCenterResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithLocationResponseDto.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/main/java/com/somemore/review/controller/ReviewQueryApiController.java
  src/main/java/com/somemore/review/dto/condition/ReviewSearchCondition.java
  src/main/java/com/somemore/review/dto/response/ReviewResponseDto.java
  src/main/java/com/somemore/review/dto/response/ReviewWithNicknameResponseDto.java
  src/main/java/com/somemore/review/repository/ReviewRepository.java
  src/main/java/com/somemore/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/somemore/review/service/ReviewQueryService.java
  src/main/java/com/somemore/review/usecase/ReviewQueryUseCase.java
  src/main/java/com/somemore/volunteer/repository/VolunteerJpaRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepositoryImpl.java
  src/main/java/com/somemore/volunteer/service/VolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/VolunteerQueryUseCase.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepository.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImpl.java
  src/test/java/com/somemore/common/fixture/RecruitBoardFixture.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
  src/test/java/com/somemore/recruitboard/domain/RecruitBoardTest.java
  src/test/java/com/somemore/recruitboard/domain/RecruitmentInfoTest.java
  src/test/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImplTest.java
  src/test/java/com/somemore/recruitboard/service/command/CreateRecruitBoardServiceTest.java
  src/test/java/com/somemore/recruitboard/service/command/DeleteRecruitBoardServiceTest.java
  src/test/java/com/somemore/recruitboard/service/command/UpdateRecruitBoardServiceTest.java
  src/test/java/com/somemore/review/repository/ReviewRepositoryImplTest.java
  src/test/java/com/somemore/review/service/ReviewQueryServiceTest.java
  src/test/java/com/somemore/volunteer/repository/VolunteerRepositoryTest.java
  src/test/java/com/somemore/volunteer/service/VolunteerQueryServiceTest.java
Labels: Feature, 범수

#124 Feature/118 봉사 시간 기준 랭킹 조회
  src/main/java/com/somemore/volunteer/controller/VolunteerProfileQueryController.java
  src/main/java/com/somemore/volunteer/controller/VolunteerRankingQueryController.java
  src/main/java/com/somemore/volunteer/domain/Volunteer.java
  src/main/java/com/somemore/volunteer/dto/response/VolunteerRankingResponseDto.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepositoryImpl.java
  src/main/java/com/somemore/volunteer/repository/mapper/VolunteerOverviewForRankingByHours.java
  src/main/java/com/somemore/volunteer/service/VolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/VolunteerQueryUseCase.java
  src/test/java/com/somemore/volunteer/repository/VolunteerRepositoryTest.java
  src/test/java/com/somemore/volunteer/service/VolunteerQueryServiceTest.java
Labels: Feature, 재중

#123 Refactor/122 인증 유저 어노테이션 및 스웨거 관련 수정
  src/main/java/com/somemore/auth/annotation/CurrentUser.java
  src/main/java/com/somemore/center/controller/CenterSignController.java
  src/main/java/com/somemore/center/controller/PreferItemCommandApiController.java
  src/main/java/com/somemore/center/dto/request/CenterSignRequestDto.java
  src/main/java/com/somemore/global/common/response/ApiResponse.java
  src/main/java/com/somemore/interestcenter/controller/InterestCenterQueryApiController.java
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiController.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardDetailResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithCenterResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithLocationResponseDto.java
  src/main/java/com/somemore/review/controller/ReviewCommandApiController.java
  src/main/java/com/somemore/review/dto/response/ReviewResponseDto.java
  src/main/java/com/somemore/review/dto/response/ReviewWithNicknameResponseDto.java
  src/main/java/com/somemore/volunteer/controller/VolunteerProfileCommandController.java
  src/main/java/com/somemore/volunteer/controller/VolunteerProfileQueryController.java
  src/test/java/com/somemore/CustomSecurityContextFactory.java
Labels: 범수, Refactor

#119 Feature/113 커뮤니티 게시글, 댓글 조회 페이징 처리
  src/main/java/com/somemore/community/dto/response/CommunityBoardDetailResponseDto.java
  src/main/java/com/somemore/community/dto/response/CommunityBoardGetDetailResponseDto.java
  src/main/java/com/somemore/community/dto/response/CommunityBoardGetResponseDto.java
  src/main/java/com/somemore/community/dto/response/CommunityBoardResponseDto.java
  src/main/java/com/somemore/community/dto/response/CommunityCommentResponseDto.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepository.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/community/repository/comment/CommunityCommentRepository.java
  src/main/java/com/somemore/community/repository/comment/CommunityCommentRepositoryImpl.java
  src/main/java/com/somemore/community/service/board/CommunityBoardQueryService.java
  src/main/java/com/somemore/community/service/comment/CommunityCommentQueryService.java
  src/main/java/com/somemore/community/usecase/board/CommunityBoardQueryUseCase.java
  src/main/java/com/somemore/community/usecase/comment/CommunityCommentQueryUseCase.java
  src/test/java/com/somemore/common/fixture/CommunityBoardFixture.java
  src/test/java/com/somemore/common/fixture/CommunityCommentFixture.java
  src/test/java/com/somemore/community/repository/CommunityBoardRepositoryTest.java
  src/test/java/com/somemore/community/repository/CommunityCommentRepositoryTest.java
  src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/community/service/board/DeleteCommunityBoardServiceTest.java
  src/test/java/com/somemore/community/service/comment/CommunityCommentQueryServiceTest.java
Labels: Feature, 아영

#127 Fix/ CORS 해결
  src/main/java/com/somemore/global/configure/WebConfig.java
Labels: bug, 재중, Fix

#131 Feature: 서버 헬스 체크를 위한 의존성 추가
  build.gradle
Labels: Feature, 서진

#135 Bug/135 스웨거 공통 응답 데이터 필드 수정
  src/main/java/com/somemore/global/common/response/ApiResponse.java
Labels: bug, 범수

#132 Feature/129 봉사 지원 승인/거절
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/recruitboard/usecase/query/RecruitBoardQueryUseCase.java
  src/main/java/com/somemore/volunteerapply/controller/CenterVolunteerApplyCommandApiController.java
  src/main/java/com/somemore/volunteerapply/service/ApproveVolunteerApplyService.java
  src/main/java/com/somemore/volunteerapply/service/RejectVolunteerApplyService.java
  src/main/java/com/somemore/volunteerapply/usecase/ApproveVolunteerApplyUseCase.java
  src/main/java/com/somemore/volunteerapply/usecase/RejectVolunteerApplyUseCase.java
  src/test/java/com/somemore/volunteerapply/controller/CenterVolunteerApplyCommandApiControllerTest.java
  src/test/java/com/somemore/volunteerapply/service/ApproveVolunteerApplyServiceTest.java
  src/test/java/com/somemore/volunteerapply/service/RejectVolunteerApplyServiceTest.java
Labels: Feature, 범수

#133 Feature/120 커뮤니티 게시글, 댓글 CRUD 엔드포인트 생성
  src/main/java/com/somemore/community/controller/CommunityBoardCommandApiController.java
  src/main/java/com/somemore/community/controller/CommunityBoardQueryApiController.java
  src/main/java/com/somemore/community/controller/CommunityCommentCommandApiController.java
  src/main/java/com/somemore/community/controller/CommunityCommentQueryApiController.java
  src/main/java/com/somemore/community/dto/request/CommunityCommentCreateRequestDto.java
  src/main/java/com/somemore/community/dto/response/CommunityBoardDetailResponseDto.java
  src/main/java/com/somemore/community/service/comment/CreateCommunityCommentService.java
  src/main/java/com/somemore/community/service/comment/DeleteCommunityCommentService.java
  src/main/java/com/somemore/community/service/comment/UpdateCommunityCommentService.java
  src/main/java/com/somemore/community/usecase/comment/CreateCommunityCommentUseCase.java
  src/main/java/com/somemore/community/usecase/comment/DeleteCommunityCommentUseCase.java
  src/main/java/com/somemore/community/usecase/comment/UpdateCommunityCommentUseCase.java
  src/test/java/com/somemore/community/controller/CommunityBoardCommandApiControllerTest.java
  src/test/java/com/somemore/community/controller/CommunityBoardQueryApiControllerTest.java
  src/test/java/com/somemore/community/controller/CommunityCommentCommandApiControllerTest.java
  src/test/java/com/somemore/community/controller/CommunityCommentQueryApiControllerTest.java
  src/test/java/com/somemore/community/service/comment/CommunityCommentQueryServiceTest.java
  src/test/java/com/somemore/community/service/comment/CreateCommunityCommentServiceTest.java
  src/test/java/com/somemore/community/service/comment/DeleteCommunityCommentServiceTest.java
  src/test/java/com/somemore/community/service/comment/UpdateCommunityCommentServiceTest.java
Labels: Feature, 아영

#141 cicd: 배포테스트용 커밋
  .github/workflows/CD.yml
Labels: 서진, CICD

#139 Feature/136 기관 마이페이지 프로필 수정
  src/main/java/com/somemore/center/controller/CenterProfileCommandApiController.java
  src/main/java/com/somemore/center/domain/Center.java
  src/main/java/com/somemore/center/dto/request/CenterProfileUpdateRequestDto.java
  src/main/java/com/somemore/center/service/command/UpdateCenterProfileService.java
  src/main/java/com/somemore/center/usecase/command/UpdateCenterProfileUseCase.java
  src/test/java/com/somemore/center/controller/CenterProfileCommandApiControllerTest.java
  src/test/java/com/somemore/center/service/command/UpdateCenterProfileServiceTest.java
Labels: Feature, 아영

#142 CICD/140 무중단 배포 적용
  .github/workflows/CD.yml
Labels: 서진, CICD

#147 fix(swagger): Swagger에서 http 요청으로 인한 CORS 에러
  src/main/java/com/somemore/global/configure/SwaggerConfig.java
Labels: bug

#149 fix: CORS
  src/main/java/com/somemore/global/configure/WebConfig.java
Labels: bug, 재중, Fix

#151 Feature/150 개발용 토큰 발급
  src/main/java/com/somemore/develop/controller/TokenGenerateMachine.java
Labels: Feature, 재중

#154 Feature/144 봉사자 to 기관 쪽지 송신 기능 개발
  src/main/java/com/somemore/domains/Note.java
  src/main/java/com/somemore/note/controller/NoteCommandApiController.java
  src/main/java/com/somemore/note/domain/Note.java
  src/main/java/com/somemore/note/dto/SendNoteToCenterRequestDto.java
  src/main/java/com/somemore/note/repository/NoteJpaRepository.java
  src/main/java/com/somemore/note/repository/NoteRepository.java
  src/main/java/com/somemore/note/repository/NoteRepositoryImpl.java
  src/main/java/com/somemore/note/service/SendNoteToCenterService.java
  src/main/java/com/somemore/note/usecase/SendNoteToCenterUseCase.java
  src/test/java/com/somemore/note/controller/NoteCommandApiControllerTest.java
  src/test/java/com/somemore/note/service/SendNoteToCenterServiceTest.java
Labels: Feature, 서진

#160 feat(CORS): PATCH 메서드 추가
  src/main/java/com/somemore/global/configure/WebConfig.java
Labels: Feature, 재중, Fix

#158 Bug/152 커뮤니티 페이징 처리 버그 수정
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/community/repository/comment/CommunityCommentRepositoryImpl.java
  src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/community/service/comment/CommunityCommentQueryServiceTest.java
Labels: bug, 아영

#164 feat/162 서브 도메인 쿠키 공유
  src/main/java/com/somemore/auth/cookie/CookieService.java
Labels: Feature, 재중

#169 Refactor/168 봉사자 지원 조회 기능 수정
  src/main/java/com/somemore/global/common/response/ApiResponse.java
  src/main/java/com/somemore/volunteerapply/controller/VolunteerApplyQueryApiController.java
Labels: 범수, Refactor

#177 feat/175: AccessToken으로 만들어진 SCH의 Authentication으로부터 userId와 role 조회
  src/main/java/com/somemore/auth/controller/UserInfoQueryController.java
  src/main/java/com/somemore/auth/dto/UserInfoResponseDto.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
Labels: Feature, 재중

#176 Bug/152 커뮤니티 페이징 오류 수정
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/community/repository/comment/CommunityCommentRepositoryImpl.java
  src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/community/service/comment/CommunityCommentQueryServiceTest.java
Labels: bug, 아영

#181 [BUG] 위치 기반 조회시 모집중이 아닌 데이터도 조회되는 문제 해결
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardQueryApiController.java
  src/main/java/com/somemore/recruitboard/dto/condition/RecruitBoardNearByCondition.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/test/java/com/somemore/common/fixture/LocalDateTimeFixture.java
Labels: bug, 범수

#183 Feature/148 봉사 활동 정산하기
  build.gradle
  src/main/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeService.java
  src/main/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeUseCase.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/global/redis/config/RedisConfig.java
  src/main/java/com/somemore/volunteer/service/UpdateVolunteerLockService.java
  src/main/java/com/somemore/volunteer/usecase/UpdateVolunteerUseCase.java
  src/main/java/com/somemore/volunteerapply/controller/CenterVolunteerApplyCommandApiController.java
  src/main/java/com/somemore/volunteerapply/dto/request/VolunteerApplySettleRequestDto.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepository.java
  src/main/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImpl.java
  src/main/java/com/somemore/volunteerapply/service/VolunteerApplyQueryService.java
  src/main/java/com/somemore/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
  src/test/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeServiceTest.java
  src/test/java/com/somemore/volunteer/domain/VolunteerTest.java
  src/test/java/com/somemore/volunteer/service/UpdateVolunteerLockServiceTest.java
  src/test/java/com/somemore/volunteerapply/controller/CenterVolunteerApplyCommandApiControllerTest.java
  src/test/java/com/somemore/volunteerapply/repository/VolunteerApplyRepositoryImplTest.java
  src/test/java/com/somemore/volunteerapply/service/VolunteerApplyQueryServiceTest.java
Labels: Feature, 범수

#184 Feature/156 봉사자와 기관의 자신에게 온 쪽지 목록
  src/main/java/com/somemore/global/common/entity/BaseEntity.java
  src/main/java/com/somemore/note/controller/NoteQueryApiController.java
  src/main/java/com/somemore/note/repository/NoteRepository.java
  src/main/java/com/somemore/note/repository/NoteRepositoryImpl.java
  src/main/java/com/somemore/note/repository/mapper/NoteReceiverViewForCenter.java
  src/main/java/com/somemore/note/repository/mapper/NoteReceiverViewForVolunteer.java
  src/main/java/com/somemore/note/service/NoteQueryService.java
  src/main/java/com/somemore/note/usecase/NoteQueryUseCase.java
  src/test/java/com/somemore/note/controller/NoteQueryApiControllerTest.java
  src/test/java/com/somemore/note/repository/NoteRepositoryImplTest.java
  src/test/java/com/somemore/note/service/NoteQueryServiceTest.java
Labels: Feature, 서진

#170 Feature/161 알림 읽음 처리
  src/main/java/com/somemore/auth/controller/UserInfoQueryController.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/notification/controller/NotificationCommandController.java
  src/main/java/com/somemore/notification/controller/NotificationQueryController.java
  src/main/java/com/somemore/notification/dto/NotificationIdsRequestDto.java
  src/main/java/com/somemore/notification/repository/NotificationRepository.java
  src/main/java/com/somemore/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/somemore/notification/service/NotificationCommandService.java
  src/main/java/com/somemore/notification/service/NotificationQueryService.java
  src/main/java/com/somemore/notification/usecase/NotificationCommandUseCase.java
  src/test/java/com/somemore/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/somemore/notification/service/NotificationCommandServiceTest.java
Labels: Feature, 재중

#185 feat 182/ cookie의 accessToken 추출
  src/main/java/com/somemore/auth/jwt/domain/EncodedToken.java
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
Labels: Feature, 재중

#187 fix/ shouldNotFilter 수정
  src/main/java/com/somemore/auth/jwt/domain/EncodedToken.java
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
Labels: bug, 재중, Fix

#193 Feature/188 쪽지 상세 보기 기능 구현
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/global/exception/NoSuchElementException.java
  src/main/java/com/somemore/global/handler/GlobalExceptionHandler.java
  src/main/java/com/somemore/note/controller/NoteQueryApiController.java
  src/main/java/com/somemore/note/repository/NoteRepository.java
  src/main/java/com/somemore/note/repository/NoteRepositoryImpl.java
  src/main/java/com/somemore/note/repository/mapper/NoteDetailViewForCenter.java
  src/main/java/com/somemore/note/repository/mapper/NoteDetailViewForVolunteer.java
  src/main/java/com/somemore/note/service/NoteQueryService.java
  src/main/java/com/somemore/note/usecase/NoteQueryUseCase.java
  src/test/java/com/somemore/note/controller/NoteQueryApiControllerTest.java
  src/test/java/com/somemore/note/repository/NoteRepositoryImplTest.java
  src/test/java/com/somemore/note/service/NoteQueryServiceTest.java
Labels: Feature, 서진

#196 BUG/194 리뷰 응답 DTO 수정
  src/main/java/com/somemore/review/dto/response/ReviewResponseDto.java
  src/test/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeServiceTest.java
  src/test/java/com/somemore/volunteer/service/UpdateVolunteerLockServiceTest.java
Labels: 범수, Fix

#202 Refactor/201 쪽지 상세조회시 읽음처리 기능 추가
  src/main/java/com/somemore/note/domain/Note.java
  src/main/java/com/somemore/note/repository/NoteRepository.java
  src/main/java/com/somemore/note/repository/NoteRepositoryImpl.java
  src/main/java/com/somemore/note/service/NoteMarkAsReadService.java
  src/main/java/com/somemore/note/service/NoteQueryService.java
  src/main/java/com/somemore/note/usecase/NoteMarkAsReadUseCase.java
  src/test/java/com/somemore/note/service/NoteMarkAsReadServiceTest.java
Labels: 서진, Refactor

#203 Feature/189 봉사 후기 요청 이벤트, 알림
  src/main/java/com/somemore/facade/event/VolunteerReviewRequestEvent.java
  src/main/java/com/somemore/facade/volunteerapply/SettleVolunteerApplyFacadeService.java
  src/main/java/com/somemore/global/common/event/ServerEvent.java
  src/main/java/com/somemore/notification/converter/MessageConverter.java
  src/main/java/com/somemore/notification/domain/NotificationSubType.java
  src/main/java/com/somemore/notification/handler/NotificationHandlerImpl.java
  src/main/java/com/somemore/volunteerapply/event/VolunteerApplyStatusChangeEvent.java
  src/main/java/com/somemore/volunteerapply/service/ApproveVolunteerApplyService.java
  src/test/java/com/somemore/notification/converter/MessageConverterTest.java
  src/test/java/com/somemore/notification/handler/NotificationHandlerTest.java
  src/test/java/com/somemore/notification/service/NotificationCommandServiceTest.java
  src/test/java/com/somemore/notification/service/NotificationQueryServiceTest.java
Labels: Feature, 범수, 재중

#207 Refactor/206 봉사활동 모집글 수정 기능 수정
  src/main/java/com/somemore/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/recruitboard/domain/RecruitmentInfo.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
  src/test/java/com/somemore/recruitboard/domain/RecruitmentInfoTest.java
  src/test/java/com/somemore/recruitboard/service/command/UpdateRecruitBoardServiceTest.java
Labels: 범수, Refactor

#209 Big/208 쪽지 읽음처리 서비스 레이어 수정
  src/main/java/com/somemore/note/service/NoteMarkAsReadService.java
  src/main/java/com/somemore/note/service/NoteQueryService.java
Labels: bug, 서진

#211 HOTFIX/210 리뷰 페이징 조회 오류 수정
  src/main/java/com/somemore/review/dto/response/ReviewWithNicknameResponseDto.java
  src/main/java/com/somemore/review/repository/ReviewRepositoryImpl.java
Labels: 범수, Fix

#216 cicd: 환경변수 추가
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 서진, CICD, env

#214 Feature/204 댓글 알림
  src/main/java/com/somemore/community/event/CommentAddedEvent.java
  src/main/java/com/somemore/community/service/comment/CreateCommunityCommentService.java
  src/main/java/com/somemore/global/common/event/ServerEvent.java
  src/main/java/com/somemore/notification/converter/MessageConverter.java
  src/main/java/com/somemore/notification/domain/NotificationSubType.java
  src/main/java/com/somemore/notification/dto/NotificationResponseDto.java
Labels: Feature, 아영, 재중

#218 Feature/217 봉사 신청 알림
  src/main/java/com/somemore/notification/converter/MessageConverter.java
  src/main/java/com/somemore/notification/domain/NotificationSubType.java
  src/main/java/com/somemore/volunteerapply/event/VolunteerApplyEvent.java
  src/main/java/com/somemore/volunteerapply/service/ApplyVolunteerApplyService.java
Labels: Feature, 재중

#225 Feature/137 봉사활동 모집글, 커뮤니티 게시글 검색 조회 (elastic search)
  build.gradle
  src/main/java/com/somemore/SomemoreApplication.java
  src/main/java/com/somemore/community/controller/CommunityBoardQueryApiController.java
  src/main/java/com/somemore/community/domain/CommunityBoardDocument.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardDocumentRepository.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepository.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/community/scheduler/CommunityBoardUpdateScheduler.java
  src/main/java/com/somemore/community/service/board/CommunityBoardDocumentService.java
  src/main/java/com/somemore/community/service/board/CommunityBoardQueryService.java
  src/main/java/com/somemore/community/usecase/board/CommunityBoardDocumentUseCase.java
  src/main/java/com/somemore/community/usecase/board/CommunityBoardQueryUseCase.java
  src/main/java/com/somemore/global/configure/ElasticsearchConfig.java
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiController.java
  src/main/java/com/somemore/recruitboard/domain/RecruitBoardDocument.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardDocumentRepository.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepository.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/main/java/com/somemore/recruitboard/scheduler/RecruitBoardUpdateScheduler.java
  src/main/java/com/somemore/recruitboard/service/query/RecruitBoardDocumentService.java
  src/main/java/com/somemore/recruitboard/service/query/RecruitBoardQueryService.java
  src/main/java/com/somemore/recruitboard/usecase/query/RecruitBoardDocumentUseCase.java
  src/main/java/com/somemore/recruitboard/usecase/query/RecruitBoardQueryUseCase.java
  src/main/resources/application.yml
  src/test/java/com/somemore/common/fixture/CommunityBoardFixture.java
  src/test/java/com/somemore/community/controller/CommunityBoardQueryApiControllerTest.java
  src/test/java/com/somemore/community/repository/CommunityBoardDocumentRepositoryTest.java
  src/test/java/com/somemore/community/repository/CommunityBoardRepositoryTest.java
  src/test/java/com/somemore/community/scheduler/CommunityBoardUpdateSchedulerTest.java
  src/test/java/com/somemore/community/service/board/CommunityBoardDocumentServiceTest.java
  src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiControllerTest.java
  src/test/java/com/somemore/recruitboard/repository/RecruitBoardDocumentRepositoryTest.java
  src/test/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImplTest.java
  src/test/java/com/somemore/recruitboard/scheduler/RecruitBoardUpdateSchedulerTest.java
  src/test/java/com/somemore/recruitboard/service/query/RecruitBoardDocumentServiceTest.java
  src/test/java/com/somemore/recruitboard/service/query/RecruitBoardQueryServiceTest.java
  src/test/resources/application-test.yml
Labels: Feature, 아영

#230 Fix/227 봉사활동 모집글 엔드포인트 prefix 수정
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiController.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiControllerTest.java
Labels: 아영, Fix

#231 [REFACTOR] 관심 기관 삭제 기능 변경
  src/main/java/com/somemore/interestcenter/controller/InterestCenterCommandApiController.java
  src/main/java/com/somemore/interestcenter/dto/request/RegisterInterestCenterRequestDto.java
  src/main/java/com/somemore/interestcenter/repository/InterestCenterRepository.java
  src/main/java/com/somemore/interestcenter/repository/InterestCenterRepositoryImpl.java
  src/main/java/com/somemore/interestcenter/service/CancelInterestCenterService.java
  src/main/java/com/somemore/interestcenter/service/RegisterInterestCenterService.java
  src/main/java/com/somemore/interestcenter/usecase/CancelInterestCenterUseCase.java
  src/main/java/com/somemore/interestcenter/usecase/RegisterInterestCenterUseCase.java
  src/test/java/com/somemore/interestcenter/controller/InterestCenterCommandApiControllerTest.java
  src/test/java/com/somemore/interestcenter/repository/InterestCenterRepositoryImplTest.java
  src/test/java/com/somemore/interestcenter/service/CancelInterestCenterServiceTest.java
  src/test/java/com/somemore/interestcenter/service/RegisterInterestCenterServiceTest.java
Labels: 범수, Refactor

#235 Refactor/233 elasticsearch 관련 코드 주석 처리
  src/main/java/com/somemore/community/controller/CommunityBoardQueryApiController.java
  src/main/java/com/somemore/community/domain/CommunityBoardDocument.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardDocumentRepository.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepository.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/community/scheduler/CommunityBoardUpdateScheduler.java
  src/main/java/com/somemore/community/service/board/CommunityBoardDocumentService.java
  src/main/java/com/somemore/community/usecase/board/CommunityBoardDocumentUseCase.java
  src/main/java/com/somemore/global/configure/ElasticsearchConfig.java
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiController.java
  src/main/java/com/somemore/recruitboard/domain/RecruitBoardDocument.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardDocumentRepository.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepository.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/main/java/com/somemore/recruitboard/scheduler/RecruitBoardUpdateScheduler.java
  src/main/java/com/somemore/recruitboard/service/query/RecruitBoardDocumentService.java
  src/main/java/com/somemore/recruitboard/usecase/query/RecruitBoardDocumentUseCase.java
  src/test/java/com/somemore/community/controller/CommunityBoardQueryApiControllerTest.java
  src/test/java/com/somemore/community/repository/CommunityBoardDocumentRepositoryTest.java
  src/test/java/com/somemore/community/repository/CommunityBoardRepositoryTest.java
  src/test/java/com/somemore/community/scheduler/CommunityBoardUpdateSchedulerTest.java
  src/test/java/com/somemore/community/service/board/CommunityBoardDocumentServiceTest.java
  src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardSearchApiControllerTest.java
  src/test/java/com/somemore/recruitboard/repository/RecruitBoardDocumentRepositoryTest.java
  src/test/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImplTest.java
  src/test/java/com/somemore/recruitboard/scheduler/RecruitBoardUpdateSchedulerTest.java
  src/test/java/com/somemore/recruitboard/service/query/RecruitBoardDocumentServiceTest.java
  src/test/java/com/somemore/recruitboard/service/query/RecruitBoardQueryServiceTest.java
Labels: 아영, Refactor

#241 DOCS/240 README 업데이트
  README.md
Labels: Docs, 재중

#232 Feature/226 관심 기관 봉사 모집 등록 알림
  src/main/java/com/somemore/global/common/event/DomainEventSubType.java
  src/main/java/com/somemore/global/common/event/ServerEvent.java
  src/main/java/com/somemore/global/common/event/ServerEventType.java
  src/main/java/com/somemore/global/redis/config/RedisConfig.java
  src/main/java/com/somemore/global/redis/registrar/RedisListenerRegistrar.java
  src/main/java/com/somemore/interestcenter/event/converter/CreateRecruitBoardMessageConverter.java
  src/main/java/com/somemore/interestcenter/event/domain/InterestCenterCreateRecruitBoardEvent.java
  src/main/java/com/somemore/interestcenter/event/handler/CreateRecruitBoardHandler.java
  src/main/java/com/somemore/interestcenter/event/handler/CreateRecruitBoardHandlerImpl.java
  src/main/java/com/somemore/interestcenter/event/subscriber/RedisCreateRecruitBoardSubscriber.java
  src/main/java/com/somemore/interestcenter/repository/InterestCenterRepository.java
  src/main/java/com/somemore/interestcenter/repository/InterestCenterRepositoryImpl.java
  src/main/java/com/somemore/interestcenter/service/InterestCenterQueryService.java
  src/main/java/com/somemore/interestcenter/usecase/InterestCenterQueryUseCase.java
  src/main/java/com/somemore/notification/domain/NotificationSubType.java
  src/main/java/com/somemore/notification/event/converter/NotificationMessageConverter.java
  src/main/java/com/somemore/notification/event/handler/NotificationHandler.java
  src/main/java/com/somemore/notification/event/handler/NotificationHandlerImpl.java
  src/main/java/com/somemore/notification/event/subscriber/RedisNotificationSubscriber.java
  src/main/java/com/somemore/notification/subscriber/NotificationSubscriber.java
  src/main/java/com/somemore/recruitboard/event/CreateRecruitBoardEvent.java
  src/main/java/com/somemore/recruitboard/service/command/CreateRecruitBoardService.java
  src/main/java/com/somemore/sse/sender/SseSenderImpl.java
  src/main/java/com/somemore/volunteerapply/service/VolunteerApplyStatusChangeService.java
  src/test/java/com/somemore/interestcenter/converter/CreateRecruitBoardMessageConverterTest.java
  src/test/java/com/somemore/interestcenter/handler/CreateRecruitBoardHandlerImplTest.java
  src/test/java/com/somemore/interestcenter/service/InterestCenterQueryServiceTest.java
  src/test/java/com/somemore/interestcenter/subscriber/RedisCreateRecruitBoardSubscriberTest.java
  src/test/java/com/somemore/notification/converter/NotificationMessageConverterTest.java
  src/test/java/com/somemore/notification/handler/NotificationHandlerTest.java
  src/test/java/com/somemore/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/somemore/notification/service/NotificationQueryServiceTest.java
Labels: Feature, 재중

#244 [REFACTOR] 모집글 QueryDsl
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
Labels: 범수, Refactor

#248 Feature/242 커뮤니티 게시글 검색 조회 (RDB)
  src/main/java/com/somemore/community/controller/CommunityBoardQueryApiController.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepository.java
  src/main/java/com/somemore/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/community/service/board/CommunityBoardQueryService.java
  src/main/java/com/somemore/community/usecase/board/CommunityBoardQueryUseCase.java
  src/test/java/com/somemore/community/controller/CommunityBoardQueryApiControllerTest.java
  src/test/java/com/somemore/community/repository/CommunityBoardRepositoryTest.java
  src/test/java/com/somemore/community/service/board/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/community/service/board/DeleteCommunityBoardServiceTest.java
Labels: Feature, 아영

#255 Feature/252 프로메테우스 의존성 추가
  build.gradle
  src/main/java/com/somemore/global/aspect/LoggingAspect.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: Feature, 서진

#258 Fix/ 헬스 체크 엔드포인트 추가
  src/main/resources/application.yml
Labels: 서진, Fix

#254 [REFACTOR] 리뷰 생성 및 컨트롤러 테스트 리팩토링
  src/main/java/com/somemore/domains/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/somemore/domains/review/service/CreateReviewService.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryService.java
  src/main/java/com/somemore/global/exception/DuplicateException.java
  src/main/java/com/somemore/global/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/somemore/domains/center/controller/CenterProfileCommandApiControllerTest.java
  src/test/java/com/somemore/domains/center/controller/CenterQueryApiControllerTest.java
  src/test/java/com/somemore/domains/center/controller/PreferItemCommandApiControllerTest.java
  src/test/java/com/somemore/domains/community/controller/CommunityBoardCommandApiControllerTest.java
  src/test/java/com/somemore/domains/community/controller/CommunityBoardQueryApiControllerTest.java
  src/test/java/com/somemore/domains/community/controller/CommunityCommentCommandApiControllerTest.java
  src/test/java/com/somemore/domains/community/controller/CommunityCommentQueryApiControllerTest.java
  src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
  src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
  src/test/java/com/somemore/domains/review/controller/ReviewCommandApiControllerTest.java
  src/test/java/com/somemore/domains/review/service/CreateReviewServiceTest.java
  src/test/java/com/somemore/domains/volunteer/controller/VolunteerProfileCommandControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/controller/CenterVolunteerApplyCommandApiControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyCommandApiControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryServiceTest.java
  src/test/java/com/somemore/support/ControllerTestSupport.java
Labels: Refactor

#260 [BUG] 봉사 지원 조회
  src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiController.java
  src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
Labels: bug, 범수, Fix
