Repository prgrms-web-devcourse-final-project/WEB1_1_Bongdari_BE, pull requests merged in 2024-11, with the labels that each got.

#16 [FEATURE] 봉사활동 모집글 생성 기능
  build.gradle
  src/main/java/com/somemore/Location.java
  src/main/java/com/somemore/RecruitBoard.java
  src/main/java/com/somemore/location/domain/Location.java
  src/main/java/com/somemore/location/dto/request/LocationCreateRequestDto.java
  src/main/java/com/somemore/location/repository/LocationRepository.java
  src/main/java/com/somemore/location/service/command/CreateLocationService.java
  src/main/java/com/somemore/location/usecase/command/CreateLocationUseCase.java
  src/main/java/com/somemore/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/recruitboard/domain/RecruitStatus.java
  src/main/java/com/somemore/recruitboard/domain/VolunteerType.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepository.java
  src/main/java/com/somemore/recruitboard/service/command/CreateRecruitBoardService.java
  src/main/java/com/somemore/recruitboard/usecase/command/CreateRecruitBoardUseCase.java
  src/test/java/com/somemore/IntegrationTestSupport.java
  src/test/java/com/somemore/SomemoreApplicationTests.java
  src/test/java/com/somemore/location/repository/LocationRepositoryTest.java
  src/test/java/com/somemore/location/service/command/CreateLocationServiceTest.java
  src/test/java/com/somemore/recruitboard/domain/RecruitBoardTest.java
  src/test/java/com/somemore/recruitboard/service/command/CreateRecruitBoardServiceTest.java
  src/test/resources/application-test.yml
Labels: Feature, 범수

#17 Feature/5 커뮤니티 게시글 생성 기능
  src/main/java/com/somemore/community/domain/CommunityBoard.java
  src/main/java/com/somemore/community/dto/request/CommunityBoardCreateRequestDto.java
  src/main/java/com/somemore/community/repository/CommunityBoardRepository.java
  src/main/java/com/somemore/community/service/command/CreateCommunityBoardService.java
  src/main/java/com/somemore/community/usecase/command/CreateCommunityBoardUseCase.java
  src/main/java/com/somemore/domains/CommunityBoard.java
  src/test/java/com/somemore/community/service/command/CreateCommunityBoardServiceTest.java
Labels: Feature, 아영

#23 Feature/18 봉사 모집글 생성 기능 수정
  src/main/java/com/somemore/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/test/java/com/somemore/recruitboard/domain/RecruitBoardTest.java
  src/test/java/com/somemore/recruitboard/service/command/CreateRecruitBoardServiceTest.java
Labels: Feature, 범수

#28 Feature/27 QueryDsl 의존성 추가
  .gitignore
  build.gradle
  src/main/java/com/somemore/global/configure/QueryDslConfig.java
  src/main/java/com/somemore/location/repository/LocationJpaRepository.java
  src/main/java/com/somemore/location/repository/LocationRepository.java
  src/main/java/com/somemore/location/repository/LocationRepositoryImpl.java
Labels: Feature, 범수

#34 Fix: sonar propertie 추가
  build.gradle
Labels: Fix

#35 CICD/31 도커 이미지 업로드 과정 분리
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 서진, CICD

#30 Feature/29 JWT 기능 구현
  build.gradle
  src/main/java/com/somemore/auth/jwt/config/JwtConfig.java
  src/main/java/com/somemore/auth/jwt/domain/EncodedToken.java
  src/main/java/com/somemore/auth/jwt/domain/TokenType.java
  src/main/java/com/somemore/auth/jwt/domain/UserRole.java
  src/main/java/com/somemore/auth/jwt/generator/HmacJwtGenerator.java
  src/main/java/com/somemore/auth/jwt/generator/JwtGenerator.java
  src/main/java/com/somemore/auth/jwt/parser/DefaultJwtParser.java
  src/main/java/com/somemore/auth/jwt/parser/JwtParser.java
  src/main/java/com/somemore/auth/jwt/refresh/domain/RefreshToken.java
  src/main/java/com/somemore/auth/jwt/refresh/manager/RedisRefreshTokenManager.java
  src/main/java/com/somemore/auth/jwt/refresh/manager/RefreshTokenManager.java
  src/main/java/com/somemore/auth/jwt/refresh/refresher/DefaultJwtRefresher.java
  src/main/java/com/somemore/auth/jwt/refresh/refresher/JwtRefresher.java
  src/main/java/com/somemore/auth/jwt/refresh/repository/RefreshTokenRepository.java
  src/main/java/com/somemore/auth/jwt/service/JwtService.java
  src/main/java/com/somemore/auth/jwt/service/command/GenerateTokensOnLoginService.java
  src/main/java/com/somemore/auth/jwt/usecase/JwtUseCase.java
  src/main/java/com/somemore/auth/jwt/usecase/command/GenerateTokensOnLoginUseCase.java
  src/main/java/com/somemore/auth/jwt/validator/DefaultJwtValidator.java
  src/main/java/com/somemore/auth/jwt/validator/JwtValidator.java
  src/main/resources/application.yml
Labels: Feature, 재중

#39 fix: add env to CD.yml
  .github/workflows/CD.yml
Labels: 서진, Fix

#32 Feature/9 기관 프로필 조회 기능 구현
  src/main/java/com/somemore/center/domain/Center.java
  src/main/java/com/somemore/center/domain/PreferItem.java
  src/main/java/com/somemore/center/dto/request/PreferItemCreateRequestDto.java
  src/main/java/com/somemore/center/dto/response/CenterProfileResponseDto.java
  src/main/java/com/somemore/center/dto/response/PreferItemResponseDto.java
  src/main/java/com/somemore/center/repository/CenterRepository.java
  src/main/java/com/somemore/center/repository/PreferItemRepository.java
  src/main/java/com/somemore/center/service/command/CreatePreferItemService.java
  src/main/java/com/somemore/center/service/query/CenterQueryService.java
  src/main/java/com/somemore/center/service/query/PreferItemQueryService.java
  src/main/java/com/somemore/center/usecase/command/CreatePreferItemUseCase.java
  src/main/java/com/somemore/center/usecase/query/CenterQueryUseCase.java
  src/main/java/com/somemore/center/usecase/query/PreferItemQueryUseCase.java
  src/main/java/com/somemore/domains/Center.java
  src/main/java/com/somemore/global/exception/BadRequestException.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/test/java/com/somemore/center/domain/CenterTest.java
  src/test/java/com/somemore/center/repository/CenterRepositoryTest.java
  src/test/java/com/somemore/center/repository/PreferItemRepositoryTest.java
  src/test/java/com/somemore/center/service/command/CreatePreferItemServiceTest.java
  src/test/java/com/somemore/center/service/query/CenterQueryServiceTest.java
  src/test/java/com/somemore/center/service/query/PreferItemQueryServiceTest.java
  src/test/resources/application-test.yml
Labels: Feature, 서진

#41 Feature/40 Spring Security / OAuth2 Cli ent, Server 구현
  src/main/java/com/somemore/SomemoreApplication.java
  src/main/java/com/somemore/auth/UserRole.java
  src/main/java/com/somemore/auth/cookie/SetCookieService.java
  src/main/java/com/somemore/auth/cookie/SetCookieUseCase.java
  src/main/java/com/somemore/auth/oauth/OAuthProvider.java
  src/main/java/com/somemore/auth/oauth/handler/failure/CustomOAuthFailureHandler.java
  src/main/java/com/somemore/auth/oauth/handler/success/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/auth/oauth/naver/domain/NaverUser.java
  src/main/java/com/somemore/auth/oauth/naver/dto/response/NaverUserProfileResponseDto.java
  src/main/java/com/somemore/auth/oauth/naver/repository/NaverUserRepository.java
  src/main/java/com/somemore/auth/oauth/naver/service/command/NaverOAuth2UserInfoService.java
  src/main/java/com/somemore/auth/oauth/naver/service/command/RegisterNaverUserService.java
  src/main/java/com/somemore/auth/oauth/naver/service/query/CheckNaverUserService.java
  src/main/java/com/somemore/auth/oauth/naver/service/query/ProcessNaverOAuthUserService.java
  src/main/java/com/somemore/auth/oauth/naver/usecase/command/RegisterNaverUserUseCase.java
  src/main/java/com/somemore/auth/oauth/naver/usecase/query/CheckNaverUserUseCase.java
  src/main/java/com/somemore/auth/oauth/naver/util/OAuthResponseConverter.java
  src/main/java/com/somemore/auth/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/somemore/auth/oauth/usecase/ProcessOAuthUserUseCase.java
  src/main/java/com/somemore/auth/redirect/RedirectConfig.java
  src/main/java/com/somemore/auth/redirect/RedirectService.java
  src/main/java/com/somemore/auth/redirect/RedirectUseCase.java
  src/main/java/com/somemore/domains/Volunteer.java
  src/main/java/com/somemore/global/configure/RedisConfig.java
  src/main/java/com/somemore/global/configure/SecurityConfig.java
  src/main/java/com/somemore/volunteer/domain/Gender.java
  src/main/java/com/somemore/volunteer/domain/Tier.java
  src/main/java/com/somemore/volunteer/domain/Volunteer.java
  src/main/java/com/somemore/volunteer/domain/VolunteerDetail.java
  src/main/java/com/somemore/volunteer/dto/request/VolunteerRegisterRequestDto.java
  src/main/java/com/somemore/volunteer/repository/VolunteerDetailRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepository.java
  src/main/java/com/somemore/volunteer/service/command/RegisterVolunteerService.java
  src/main/java/com/somemore/volunteer/service/query/FindVolunteerIdService.java
  src/main/java/com/somemore/volunteer/usecase/command/RegisterVolunteerUseCase.java
  src/main/java/com/somemore/volunteer/usecase/query/FindVolunteerIdUseCase.java
  src/main/resources/application.yml
  src/test/java/com/somemore/IntegrationTestSupport.java
  src/test/java/com/somemore/volunteer/service/command/RegisterVolunteerServiceTest.java
  src/test/java/com/somemore/volunteer/service/query/FindVolunteerIdServiceTest.java
  src/test/resources/application-test.yml
Labels: Feature, 재중

#50 Feature/42 Jwt (Auth, Filter, Exception) 기능
  src/main/java/com/somemore/auth/jwt/exception/JwtErrorType.java
  src/main/java/com/somemore/auth/jwt/exception/JwtException.java
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthenticationToken.java
  src/main/java/com/somemore/auth/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/somemore/auth/jwt/generator/HmacJwtGenerator.java
  src/main/java/com/somemore/auth/jwt/parser/DefaultJwtParser.java
  src/main/java/com/somemore/auth/jwt/refresh/manager/RedisRefreshTokenManager.java
  src/main/java/com/somemore/auth/jwt/refresh/refresher/DefaultJwtRefresher.java
  src/main/java/com/somemore/auth/jwt/service/JwtService.java
  src/main/java/com/somemore/auth/jwt/usecase/JwtUseCase.java
  src/main/java/com/somemore/auth/jwt/validator/DefaultJwtValidator.java
  src/main/java/com/somemore/auth/jwt/validator/JwtValidator.java
  src/main/java/com/somemore/global/configure/SecurityConfig.java
  src/test/java/com/somemore/auth/jwt/service/JwtServiceTest.java
Labels: Feature, 재중

#54 Refactor/51 커뮤니티 게시글 id로 조회 로직 QueryDSL로 변경
  src/main/java/com/somemore/community/repository/CommunityBoardRepository.java
  src/main/java/com/somemore/community/repository/CommunityRepositoryImpl.java
  src/main/java/com/somemore/community/service/query/CommunityBoardQueryService.java
  src/test/java/com/somemore/community/repository/CommunityRepositoryTest.java
Labels: 아영, Refactor

#55 Feature/47 커뮤니티 게시글 삭제 기능
  src/main/java/com/somemore/community/domain/CommunityBoard.java
  src/main/java/com/somemore/community/service/command/DeleteCommunityBoardService.java
  src/main/java/com/somemore/community/usecase/command/DeleteCommunityBoardUseCase.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/test/java/com/somemore/community/service/command/DeleteCommunityBoardServiceTest.java
  src/test/java/com/somemore/community/service/query/CommunityBoardQueryServiceTest.java
Labels: Feature, 아영

#58 CICD/57 배포 자동화 workflow 구현
  .github/workflows/CD.yml
Labels: 서진, CICD

#59 Feature/56 커뮤니티 게시글 수정 기능
  src/main/java/com/somemore/community/domain/CommunityBoard.java
  src/main/java/com/somemore/community/dto/request/CommunityBoardUpdateRequestDto.java
  src/main/java/com/somemore/community/service/CommunityBoardQueryService.java
  src/main/java/com/somemore/community/service/CreateCommunityBoardService.java
  src/main/java/com/somemore/community/service/DeleteCommunityBoardService.java
  src/main/java/com/somemore/community/service/UpdateCommunityBoardService.java
  src/main/java/com/somemore/community/usecase/CommunityBoardQueryUseCase.java
  src/main/java/com/somemore/community/usecase/CreateCommunityBoardUseCase.java
  src/main/java/com/somemore/community/usecase/DeleteCommunityBoardUseCase.java
  src/main/java/com/somemore/community/usecase/UpdateCommunityBoardUseCase.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/test/java/com/somemore/community/service/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/community/service/CreateCommunityBoardServiceTest.java
  src/test/java/com/somemore/community/service/DeleteCommunityBoardServiceTest.java
  src/test/java/com/somemore/community/service/UpdateCommunityBoardServiceTest.java
Labels: Feature, 아영

#61 CICD/ 환경 변수 추가
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 서진, CICD

#62 Feature/53 add volunteer signin signout
  src/main/java/com/somemore/auth/cookie/CookieService.java
  src/main/java/com/somemore/auth/cookie/CookieUseCase.java
  src/main/java/com/somemore/auth/cookie/SetCookieService.java
  src/main/java/com/somemore/auth/cookie/SetCookieUseCase.java
  src/main/java/com/somemore/auth/jwt/domain/TokenType.java
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/auth/jwt/filter/UserRole.java
  src/main/java/com/somemore/auth/jwt/refresh/manager/RedisRefreshTokenManager.java
  src/main/java/com/somemore/auth/jwt/refresh/manager/RefreshTokenManager.java
  src/main/java/com/somemore/auth/jwt/refresh/repository/RefreshTokenRepository.java
  src/main/java/com/somemore/auth/jwt/service/GenerateTokensOnLoginService.java
  src/main/java/com/somemore/auth/jwt/service/JwtService.java
  src/main/java/com/somemore/auth/jwt/usecase/GenerateTokensOnLoginUseCase.java
  src/main/java/com/somemore/auth/oauth/handler/success/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/auth/oauth/naver/service/command/NaverOAuth2UserInfoService.java
  src/main/java/com/somemore/community/service/CommunityBoardQueryService.java
  src/main/java/com/somemore/global/common/response/ApiResponse.java
  src/main/java/com/somemore/volunteer/controller/VolunteerSignController.java
  src/main/java/com/somemore/volunteer/service/FindVolunteerIdService.java
  src/main/java/com/somemore/volunteer/service/GenerateOAuthUrlService.java
  src/main/java/com/somemore/volunteer/service/RegisterVolunteerService.java
  src/main/java/com/somemore/volunteer/service/SignOutVolunteerService.java
  src/main/java/com/somemore/volunteer/usecase/FindVolunteerIdUseCase.java
  src/main/java/com/somemore/volunteer/usecase/GenerateOAuthUrlUseCase.java
  src/main/java/com/somemore/volunteer/usecase/RegisterVolunteerUseCase.java
  src/main/java/com/somemore/volunteer/usecase/SignOutVolunteerUseCase.java
  src/main/resources/application.yml
  src/test/java/com/somemore/auth/cookie/CookieServiceTest.java
  src/test/java/com/somemore/auth/jwt/service/JwtServiceTest.java
  src/test/java/com/somemore/volunteer/controller/VolunteerSignControllerTest.java
  src/test/java/com/somemore/volunteer/service/FindVolunteerIdServiceTest.java
  src/test/java/com/somemore/volunteer/service/GenerateOAuthUrlServiceTest.java
  src/test/java/com/somemore/volunteer/service/RegisterVolunteerServiceTest.java
  src/test/java/com/somemore/volunteer/service/SignOutVolunteerServiceTest.java
  src/test/resources/application-test.yml
Labels: Feature, 재중

#64 Refactor/60 커뮤니티 게시글 조회 기능 리팩토링
  src/main/java/com/somemore/center/dto/response/CenterForCommunityResponseDto.java
  src/main/java/com/somemore/center/repository/CenterRepository.java
  src/main/java/com/somemore/center/repository/CenterRepositoryImpl.java
  src/main/java/com/somemore/center/service/query/CenterQueryService.java
  src/main/java/com/somemore/center/usecase/query/CenterQueryUseCase.java
  src/main/java/com/somemore/community/domain/CommunityBoardView.java
  src/main/java/com/somemore/community/dto/response/CommunityBoardGetDetailResponseDto.java
  src/main/java/com/somemore/community/dto/response/CommunityBoardGetResponseDto.java
  src/main/java/com/somemore/community/dto/response/WriterDetailDto.java
  src/main/java/com/somemore/community/repository/CommunityBoardRepository.java
  src/main/java/com/somemore/community/repository/CommunityRepositoryImpl.java
  src/main/java/com/somemore/community/service/CommunityBoardQueryService.java
  src/main/java/com/somemore/volunteer/dto/response/VolunteerForCommunityResponseDto.java
  src/main/java/com/somemore/volunteer/repository/VolunteerDetailRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerJpaRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepository.java
  src/main/java/com/somemore/volunteer/repository/VolunteerRepositoryImpl.java
  src/main/java/com/somemore/volunteer/service/FindVolunteerIdService.java
  src/main/java/com/somemore/volunteer/usecase/FindVolunteerIdUseCase.java
  src/test/java/com/somemore/center/repository/CenterRepositoryTest.java
  src/test/java/com/somemore/center/service/query/CenterQueryServiceTest.java
  src/test/java/com/somemore/community/repository/CommunityRepositoryTest.java
  src/test/java/com/somemore/community/service/CommunityBoardQueryServiceTest.java
Labels: 아영, Refactor

#66 Feature/36 s3 이미지 업로드 기능 구현
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  build.gradle
  src/main/java/com/somemore/global/configure/S3Config.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/global/exception/ImageUploadException.java
  src/main/java/com/somemore/global/handler/GlobalExceptionHandler.java
  src/main/java/com/somemore/imageupload/dto/ImageUploadRequestDto.java
  src/main/java/com/somemore/imageupload/service/ImageUploadService.java
  src/main/java/com/somemore/imageupload/usecase/ImageUploadUseCase.java
  src/main/java/com/somemore/imageupload/util/ImageUploadUtils.java
  src/main/java/com/somemore/imageupload/validator/DefaultImageUploadValidator.java
  src/main/java/com/somemore/imageupload/validator/ImageUploadValidator.java
  src/main/resources/application.yml
  src/test/java/com/somemore/imageupload/service/ImageUploadServiceTest.java
  src/test/java/com/somemore/imageupload/util/ImageUploadUtilsTest.java
  src/test/java/com/somemore/imageupload/validator/DefaultImageUploadValidatorTest.java
  src/test/resources/application-test.yml
Labels: Feature, 서진

#73 Feature/68 커뮤니티 댓글 삭제 기능
  src/main/java/com/somemore/community/domain/CommunityComment.java
  src/main/java/com/somemore/community/service/comment/DeleteCommunityCommentService.java
  src/main/java/com/somemore/community/usecase/comment/DeleteCommunityCommentUseCase.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/test/java/com/somemore/community/service/comment/DeleteCommunityCommentServiceTest.java
Labels: Feature, 아영

#74 Feature/69 기관 프로필 조회 컨트롤러 구현
  src/main/java/com/somemore/center/controller/CenterQueryApiController.java
  src/main/java/com/somemore/center/domain/Center.java
  src/main/java/com/somemore/center/dto/response/CenterProfileResponseDto.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/test/java/com/somemore/ControllerTestSupport.java
  src/test/java/com/somemore/center/controller/CenterQueryApiControllerTest.java
Labels: Feature, 서진

#72 [BUILD FAIL] Feature/49 봉사 모집글 조회 기능
  build.gradle
  src/main/java/com/somemore/center/dto/response/CenterSimpleInfoResponseDto.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/location/dto/response/LocationResponseDto.java
  src/main/java/com/somemore/location/service/command/UpdateLocationService.java
  src/main/java/com/somemore/location/service/query/LocationQueryService.java
  src/main/java/com/somemore/location/usecase/query/LocationQueryUseCase.java
  src/main/java/com/somemore/location/utils/GeoUtils.java
  src/main/java/com/somemore/recruitboard/controller/RecruitBoardQueryController.java
  src/main/java/com/somemore/recruitboard/dto/condition/RecruitBoardNearByCondition.java
  src/main/java/com/somemore/recruitboard/dto/condition/RecruitBoardSearchCondition.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardDetailResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithCenterResponseDto.java
  src/main/java/com/somemore/recruitboard/dto/response/RecruitBoardWithLocationResponseDto.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepository.java
  src/main/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/main/java/com/somemore/recruitboard/repository/mapper/RecruitBoardDetail.java
  src/main/java/com/somemore/recruitboard/repository/mapper/RecruitBoardWithCenter.java
  src/main/java/com/somemore/recruitboard/repository/mapper/RecruitBoardWithLocation.java
  src/main/java/com/somemore/recruitboard/service/query/RecruitBoardQueryService.java
  src/main/java/com/somemore/recruitboard/usecase/query/RecruitBoardQueryUseCase.java
  src/test/java/com/somemore/common/fixture/CenterFixture.java
  src/test/java/com/somemore/common/fixture/LocationFixture.java
  src/test/java/com/somemore/common/fixture/RecruitBoardFixture.java
  src/test/java/com/somemore/location/service/query/LocationQueryServiceTest.java
  src/test/java/com/somemore/recruitboard/controller/RecruitBoardQueryControllerTest.java
  src/test/java/com/somemore/recruitboard/repository/RecruitBoardRepositoryImplTest.java
  src/test/java/com/somemore/recruitboard/service/command/CreateRecruitBoardServiceTest.java
  src/test/java/com/somemore/recruitboard/service/command/DeleteRecruitBoardServiceTest.java
  src/test/java/com/somemore/recruitboard/service/command/UpdateRecruitBoardServiceTest.java
  src/test/java/com/somemore/recruitboard/service/query/RecruitBoardQueryServiceTest.java
  src/test/java/com/somemore/recruitboard/service/query/RecruitQueryServiceTest.java
Labels: Feature, 범수

#85 Feature/75 관심기관 등록, 취소 기능 구현
  src/main/java/com/somemore/domains/InterestCenter.java
  src/main/java/com/somemore/global/common/response/ApiResponse.java
  src/main/java/com/somemore/global/exception/DuplicateException.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/global/handler/GlobalExceptionHandler.java
  src/main/java/com/somemore/interestcenter/controller/InterestCenterCommandApiController.java
  src/main/java/com/somemore/interestcenter/domain/InterestCenter.java
  src/main/java/com/somemore/interestcenter/dto/request/RegisterInterestCenterRequestDto.java
  src/main/java/com/somemore/interestcenter/dto/response/RegisterInterestCenterResponseDto.java
  src/main/java/com/somemore/interestcenter/repository/InterestCenterJpaRepository.java
  src/main/java/com/somemore/interestcenter/repository/InterestCenterRepository.java
  src/main/java/com/somemore/interestcenter/repository/InterestCenterRepositoryImpl.java
  src/main/java/com/somemore/interestcenter/service/CancelInterestCenterService.java
  src/main/java/com/somemore/interestcenter/service/RegisterInterestCenterService.java
  src/main/java/com/somemore/interestcenter/usecase/CancelInterestCenterUseCase.java
  src/main/java/com/somemore/interestcenter/usecase/RegisterInterestCenterUseCase.java
  src/test/java/com/somemore/interestcenter/controller/InterestCenterCommandApiControllerTest.java
  src/test/java/com/somemore/interestcenter/service/CancelInterestCenterServiceTest.java
  src/test/java/com/somemore/interestcenter/service/RegisterInterestCenterServiceTest.java
Labels: Feature, 서진

#90 cicd: workflow 환경변수 추가
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 서진, CICD

#92 CICD/ workflow 환경변수 추가
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 서진, CICD

#91 Feature/89 스웨거 API 테스트를 위한 봉사자 / 기관 토큰 발급
  src/main/java/com/somemore/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/auth/util/DevAccountSetUpConfig.java
  src/main/java/com/somemore/center/repository/CenterJpaRepository.java
  src/main/java/com/somemore/global/configure/SwaggerConfig.java
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: Feature, 범수

#94 hotfix: fix typo
  src/main/java/com/somemore/auth/util/DevAccountSetUpConfig.java
Labels: bug
