Repository prgrms-web-devcourse-final-project/WEB1_1_Bongdari_BE, pull requests merged in 2025-02, with the labels that each got.

#347 [ REFACTOR] 유저 테이블에 알맞게 알림 로직 수정
  src/main/java/com/somemore/domains/notification/controller/NotificationCommandController.java
  src/main/java/com/somemore/domains/notification/dto/NotificationResponseDto.java
  src/main/java/com/somemore/domains/notification/repository/NotificationJpaRepository.java
  src/main/java/com/somemore/domains/notification/repository/NotificationRepository.java
  src/main/java/com/somemore/domains/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/somemore/domains/notification/service/NotificationCommandService.java
  src/main/java/com/somemore/domains/notification/service/NotificationQueryService.java
  src/main/java/com/somemore/domains/notification/usecase/NotificationQueryUseCase.java
  src/test/java/com/somemore/domains/notification/handler/NotificationHandlerTest.java
  src/test/java/com/somemore/domains/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/somemore/domains/notification/service/NotificationCommandServiceTest.java
Labels: Feature, 재중

#352 [FEATURE] 액세스 토큰 리프레시
  src/main/java/com/somemore/global/auth/jwt/controller/TokenController.java
  src/main/java/com/somemore/global/auth/jwt/domain/EncodedToken.java
  src/main/java/com/somemore/global/auth/jwt/dto/AccessTokenRequestDto.java
  src/main/java/com/somemore/global/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/global/auth/jwt/refresher/DefaultJwtRefresher.java
  src/main/java/com/somemore/global/auth/jwt/service/JwtService.java
  src/main/java/com/somemore/global/auth/jwt/usecase/JwtUseCase.java
  src/main/java/com/somemore/global/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/somemore/global/auth/jwt/service/JwtServiceTest.java
Labels: Feature, 재중

#350 [REFACTOR] 리뷰 조회 리팩토링
  src/main/java/com/somemore/domains/review/controller/ReviewQueryApiController.java
  src/main/java/com/somemore/domains/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/com/somemore/domains/review/dto/response/ReviewDetailWithNicknameResponseDto.java
  src/main/java/com/somemore/domains/review/service/ReviewQueryService.java
  src/main/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepository.java
  src/main/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepositoryImpl.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryService.java
  src/main/java/com/somemore/domains/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
  src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepository.java
  src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImpl.java
  src/main/java/com/somemore/volunteer/service/NEWVolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/NEWVolunteerQueryUseCase.java
  src/test/java/com/somemore/domains/review/service/ReviewQueryServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepositoryImplTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryServiceTest.java
  src/test/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImplTest.java
  src/test/java/com/somemore/volunteer/service/NEWVolunteerQueryServiceTest.java
Labels: Refactor

#354 [FEATURE] IDPW 로그인시 쿠키로 임시 토큰 발급
  src/main/java/com/somemore/global/auth/idpw/filter/IdPwAuthFilter.java
  src/main/java/com/somemore/global/auth/jwt/domain/TokenType.java
  src/main/java/com/somemore/global/config/SecurityConfig.java
Labels: Feature, 재중

#358 [FIX] 액세스 토큰 쿠키 명명 수정으로 필터 로직 수정
  src/main/java/com/somemore/global/auth/jwt/domain/TokenType.java
  src/main/java/com/somemore/global/auth/jwt/filter/JwtAuthFilter.java
Labels: bug, Fix

#359 [REFACTOR] 관심 기관 리팩토링
  src/main/java/com/somemore/center/repository/NEWCenterRepository.java
  src/main/java/com/somemore/center/repository/NEWCenterRepositoryImpl.java
  src/main/java/com/somemore/center/repository/record/CenterOverviewInfo.java
  src/main/java/com/somemore/center/service/NEWCenterQueryService.java
  src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
  src/main/java/com/somemore/domains/center/repository/center/CenterRepository.java
  src/main/java/com/somemore/domains/center/repository/center/CenterRepositoryImpl.java
  src/main/java/com/somemore/domains/center/service/query/CenterQueryService.java
  src/main/java/com/somemore/domains/center/usecase/query/CenterQueryUseCase.java
  src/main/java/com/somemore/domains/interestcenter/controller/InterestCenterCommandApiController.java
  src/main/java/com/somemore/domains/interestcenter/controller/InterestCenterQueryApiController.java
  src/main/java/com/somemore/domains/interestcenter/dto/response/InterestCentersResponseDto.java
  src/main/java/com/somemore/domains/interestcenter/service/CancelInterestCenterService.java
  src/main/java/com/somemore/domains/interestcenter/service/InterestCenterQueryService.java
  src/main/java/com/somemore/domains/interestcenter/service/RegisterInterestCenterService.java
  src/test/java/com/somemore/center/repository/NEWCenterRepositoryImplTest.java
  src/test/java/com/somemore/center/service/NEWCenterQueryServiceTest.java
  src/test/java/com/somemore/domains/center/service/query/CenterQueryServiceTest.java
  src/test/java/com/somemore/domains/interestcenter/controller/InterestCenterCommandApiControllerTest.java
  src/test/java/com/somemore/domains/interestcenter/controller/InterestCenterQueryApiControllerTest.java
  src/test/java/com/somemore/domains/interestcenter/service/CancelInterestCenterServiceTest.java
  src/test/java/com/somemore/domains/interestcenter/service/InterestCenterQueryServiceTest.java
  src/test/java/com/somemore/domains/interestcenter/service/RegisterInterestCenterServiceTest.java
Labels: 범수, Refactor

#366 [REFACTOR] 쪽지 리팩토링
  src/main/java/com/somemore/domains/note/controller/NoteCommandApiController.java
  src/main/java/com/somemore/domains/note/controller/NoteQueryApiController.java
  src/main/java/com/somemore/domains/note/repository/NoteRepositoryImpl.java
  src/main/java/com/somemore/domains/note/service/NoteMarkAsReadService.java
  src/main/java/com/somemore/domains/note/service/SendNoteToCenterService.java
  src/main/java/com/somemore/domains/note/service/SendNoteToVolunteerService.java
  src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepository.java
  src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImpl.java
  src/main/java/com/somemore/volunteer/service/NEWVolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/NEWVolunteerQueryUseCase.java
  src/test/java/com/somemore/domains/note/controller/NoteCommandApiControllerTest.java
  src/test/java/com/somemore/domains/note/controller/NoteQueryApiControllerTest.java
  src/test/java/com/somemore/domains/note/repository/NoteRepositoryImplTest.java
  src/test/java/com/somemore/domains/note/service/NoteQueryServiceTest.java
  src/test/java/com/somemore/domains/note/service/SendNoteToCenterServiceTest.java
  src/test/java/com/somemore/domains/note/service/SendNoteToVolunteerServiceTest.java
  src/test/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImplTest.java
  src/test/java/com/somemore/volunteer/service/NEWVolunteerQueryServiceTest.java
Labels: 범수, Refactor

#362 [REFACTOR] 유저 테이블 변경에 따른 알림 로직 변경 및 개선
  src/main/java/com/somemore/center/service/NEWCenterQueryService.java
  src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
  src/main/java/com/somemore/domains/community/event/CommentAddedEvent.java
  src/main/java/com/somemore/domains/community/service/comment/CreateCommunityCommentService.java
  src/main/java/com/somemore/domains/interestcenter/event/domain/InterestCenterCreateRecruitBoardEvent.java
  src/main/java/com/somemore/domains/interestcenter/event/handler/CreateRecruitBoardHandlerImpl.java
  src/main/java/com/somemore/domains/notification/controller/NotificationQueryController.java
  src/main/java/com/somemore/domains/notification/event/converter/NotificationMessageConverter.java
  src/main/java/com/somemore/domains/recruitboard/event/CreateRecruitBoardEvent.java
  src/main/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardService.java
  src/main/java/com/somemore/domains/volunteerapply/event/VolunteerApplyEvent.java
  src/main/java/com/somemore/domains/volunteerapply/event/VolunteerApplyStatusChangeEvent.java
  src/main/java/com/somemore/domains/volunteerapply/event/VolunteerReviewRequestEvent.java
  src/main/java/com/somemore/domains/volunteerapply/service/ApplyVolunteerApplyService.java
  src/main/java/com/somemore/domains/volunteerapply/service/SettleVolunteerApplyFacadeService.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyStatusChangeService.java
  src/main/java/com/somemore/domains/volunteerrecord/event/VolunteerRecordCreateEvent.java
  src/main/java/com/somemore/domains/volunteerrecord/event/VolunteerRecordEventPublisher.java
  src/main/java/com/somemore/global/auth/annotation/UserIdArgumentResolver.java
  src/test/java/com/somemore/domains/interestcenter/handler/CreateRecruitBoardHandlerImplTest.java
  src/test/java/com/somemore/domains/notification/converter/NotificationMessageConverterTest.java
  src/test/java/com/somemore/domains/notification/handler/NotificationHandlerTest.java
Labels: 재중, Refactor

#363 [REFACTOR] 커뮤니티 리팩토링
  src/main/java/com/somemore/domains/community/controller/CommunityBoardCommandApiController.java
  src/main/java/com/somemore/domains/community/controller/CommunityCommentCommandApiController.java
  src/main/java/com/somemore/domains/community/domain/CommunityBoard.java
  src/main/java/com/somemore/domains/community/dto/request/CommunityBoardCreateRequestDto.java
  src/main/java/com/somemore/domains/community/dto/response/CommunityBoardDetailResponseDto.java
  src/main/java/com/somemore/domains/community/dto/response/CommunityCommentResponseDto.java
  src/main/java/com/somemore/domains/community/repository/board/CommunityBoardRepositoryImpl.java
  src/main/java/com/somemore/domains/community/repository/comment/CommunityCommentRepositoryImpl.java
  src/main/java/com/somemore/domains/community/service/board/CreateCommunityBoardService.java
  src/main/java/com/somemore/domains/community/service/board/UpdateCommunityBoardService.java
  src/main/java/com/somemore/domains/community/usecase/board/CreateCommunityBoardUseCase.java
  src/main/java/com/somemore/domains/community/usecase/board/UpdateCommunityBoardUseCase.java
  src/test/java/com/somemore/domains/community/controller/CommunityBoardCommandApiControllerTest.java
  src/test/java/com/somemore/domains/community/controller/CommunityCommentCommandApiControllerTest.java
  src/test/java/com/somemore/domains/community/repository/CommunityBoardRepositoryTest.java
  src/test/java/com/somemore/domains/community/repository/CommunityCommentRepositoryTest.java
  src/test/java/com/somemore/domains/community/service/board/CommunityBoardQueryServiceTest.java
  src/test/java/com/somemore/domains/community/service/board/CreateCommunityBoardServiceTest.java
  src/test/java/com/somemore/domains/community/service/board/DeleteCommunityBoardServiceTest.java
  src/test/java/com/somemore/domains/community/service/board/UpdateCommunityBoardServiceTest.java
  src/test/java/com/somemore/domains/community/service/comment/CommunityCommentQueryServiceTest.java
  src/test/java/com/somemore/domains/community/service/comment/CreateCommunityCommentServiceTest.java
  src/test/java/com/somemore/domains/community/service/comment/DeleteCommunityCommentServiceTest.java
  src/test/java/com/somemore/domains/community/service/comment/UpdateCommunityCommentServiceTest.java
  src/test/java/com/somemore/support/fixture/CommunityBoardFixture.java
Labels: 아영, Refactor

#367 [FEATURE] 이미지 업로드 (프로필, 공통)
  src/main/java/com/somemore/center/controller/CenterCommandApiController.java
  src/main/java/com/somemore/center/service/UpdateCenterProfileImgService.java
  src/main/java/com/somemore/center/usecase/UpdateCenterProfileImgUseCase.java
  src/main/java/com/somemore/domains/center/controller/CenterProfileCommandApiController.java
  src/main/java/com/somemore/global/auth/sign/up/SignUpService.java
  src/main/java/com/somemore/global/exception/ImageUploadException.java
  src/main/java/com/somemore/global/imageupload/controller/GetPresignedUrlController.java
  src/main/java/com/somemore/global/imageupload/service/ImageUploadService.java
  src/main/java/com/somemore/global/imageupload/service/PresignedUrl.java
  src/main/java/com/somemore/global/imageupload/usecase/ImageUploadUseCase.java
  src/main/java/com/somemore/user/controller/UserCommandController.java
  src/main/java/com/somemore/user/domain/User.java
  src/main/java/com/somemore/user/domain/UserAuthInfo.java
  src/main/java/com/somemore/user/domain/UserCommonAttribute.java
  src/main/java/com/somemore/user/dto/basicinfo/CommonBasicInfoRequestDto.java
  src/main/java/com/somemore/user/dto/request/ImgUrlRequestDto.java
  src/main/java/com/somemore/user/dto/request/UpdateProfileImgUrlRequestDto.java
  src/main/java/com/somemore/user/service/RegisterUserService.java
  src/main/java/com/somemore/user/service/UpdateBasicInfoService.java
  src/main/java/com/somemore/user/service/UpdateProfileImgUrlService.java
  src/main/java/com/somemore/user/usecase/RegisterUserUseCase.java
  src/main/java/com/somemore/user/usecase/UpdateProfileImgUrlUseCase.java
  src/test/java/com/somemore/center/controller/CenterCommandApiControllerTest.java
  src/test/java/com/somemore/domains/interestcenter/handler/CreateRecruitBoardHandlerImplTest.java
  src/test/java/com/somemore/domains/notification/converter/NotificationMessageConverterTest.java
  src/test/java/com/somemore/domains/notification/handler/NotificationHandlerTest.java
  src/test/java/com/somemore/global/imageupload/service/ImageUploadServiceTest.java
  src/test/java/com/somemore/global/imageupload/service/PresignedUrlTest.java
  src/test/java/com/somemore/user/repository/user/UserRepositoryImplTest.java
  src/test/java/com/somemore/user/service/RegisterUserServiceTest.java
  src/test/java/com/somemore/user/service/UpdateBasicInfoServiceTest.java
  src/test/java/com/somemore/user/service/UpdateProfileImgServiceTest.java
  src/test/java/com/somemore/user/service/UpdateProfileImgUrlServiceTest.java
  src/test/java/com/somemore/user/service/UserQueryServiceTest.java
  src/test/java/com/somemore/user/service/ValidateBasicInfoServiceTest.java
Labels: Feature, 재중, Refactor

#369 [FIX] user secured 문제 해결
  src/main/java/com/somemore/global/imageupload/controller/GetPresignedUrlController.java
  src/main/java/com/somemore/user/controller/UserCommandController.java
Labels: bug, Fix

#370 [REFACTOR] 검색 리팩토링
  src/main/java/com/somemore/center/repository/NEWCenterRepository.java
  src/main/java/com/somemore/center/repository/NEWCenterRepositoryImpl.java
  src/main/java/com/somemore/center/service/NEWCenterQueryService.java
  src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
  src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiController.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardResponseDto.java
  src/main/java/com/somemore/domains/search/controller/RecruitBoardSearchApiController.java
  src/main/java/com/somemore/domains/search/repository/SearchBoardRepository.java
  src/main/java/com/somemore/domains/search/repository/SearchBoardRepositoryImpl.java
  src/main/java/com/somemore/domains/search/service/RecruitBoardDocumentService.java
  src/main/java/com/somemore/domains/search/usecase/RecruitBoardDocumentUseCase.java
  src/test/java/com/somemore/center/repository/NEWCenterRepositoryImplTest.java
  src/test/java/com/somemore/center/service/NEWCenterQueryServiceTest.java
  src/test/java/com/somemore/domains/search/controller/RecruitBoardSearchApiControllerTest.java
  src/test/java/com/somemore/domains/search/repository/SearchBoardRepositoryTest.java
  src/test/java/com/somemore/domains/search/service/CommunityBoardDocumentServiceTest.java
  src/test/java/com/somemore/domains/search/service/RecruitBoardDocumentServiceTest.java
Labels: 아영, Refactor

#374 [FIX] 유저 정보 업데이트 오류 수정
  src/main/java/com/somemore/user/dto/basicinfo/VolunteerBasicInfoRequestDto.java
Labels: bug

#375 [FIX] 유저 정보 업데이트 오류 수정
  src/main/java/com/somemore/user/dto/basicinfo/CenterBasicInfoRequestDto.java
Labels: bug
