Repository prgrms-web-devcourse-final-project/WEB1_1_Bongdari_BE, pull requests merged in 2025-01, with the labels that each got.

#264 Feature/261 리디렉션 수정
  src/main/java/com/somemore/global/auth/oauth/handler/CustomOAuthFailureHandler.java
  src/main/java/com/somemore/global/auth/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/global/auth/redirect/RedirectService.java
  src/main/java/com/somemore/global/auth/redirect/RedirectUseCase.java
  src/main/java/com/somemore/global/config/SecurityConfig.java
Labels: Feature, 재중, Refactor

#266 [DELETE] 개발용 토큰 발급기
  src/main/java/com/somemore/develop/controller/TokenGenerateMachine.java
Labels: Feature

#270 Refactor/252 Logging 설정 추가및 리팩토링
  .gitignore
  build.gradle
  src/main/java/com/somemore/global/aspect/LoggingAspect.java
  src/main/java/com/somemore/global/aspect/log/LoggingAspect.java
  src/main/java/com/somemore/global/aspect/log/extractor/ParameterExtractor.java
  src/main/java/com/somemore/global/aspect/log/extractor/RequestExtractor.java
  src/main/java/com/somemore/global/aspect/log/extractor/ResponseExtractor.java
  src/main/java/com/somemore/global/aspect/log/utils/SensitiveDataMasker.java
  src/main/java/com/somemore/global/common/response/LoggedResponse.java
  src/main/resources/logback-spring.xml
  src/test/java/com/somemore/global/aspect/log/SensitiveDataMaskerTest.java
Labels: 서진, Refactor

#272 Fix/271 logback의 loki 관련 설정 수정
  src/main/resources/logback-spring.xml
Labels: Fix

#275 Fix/271 logback의 loki 관련 설정 수정
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  src/main/resources/logback-spring.xml
Labels: Fix

#269 [FEATURE] 모집글 시간 필드 추가
  src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiController.java
  src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiController.java
  src/main/java/com/somemore/domains/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/domains/recruitboard/domain/RecruitmentInfo.java
  src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardDetailResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardWithCenterResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardWithLocationResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/service/DeleteRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/service/RecruitBoardDocumentService.java
  src/main/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryService.java
  src/main/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/service/command/DeleteRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/service/command/UpdateRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidator.java
  src/main/java/com/somemore/domains/recruitboard/usecase/CreateRecruitBoardUseCase.java
  src/main/java/com/somemore/domains/recruitboard/usecase/DeleteRecruitBoardUseCase.java
  src/main/java/com/somemore/domains/recruitboard/usecase/RecruitBoardDocumentUseCase.java
  src/main/java/com/somemore/domains/recruitboard/usecase/RecruitBoardQueryUseCase.java
  src/main/java/com/somemore/domains/recruitboard/usecase/UpdateRecruitBoardUseCase.java
  src/main/java/com/somemore/domains/recruitboard/usecase/command/DeleteRecruitBoardUseCase.java
  src/main/java/com/somemore/domains/recruitboard/usecase/command/UpdateRecruitBoardUseCase.java
  src/main/java/com/somemore/domains/review/domain/Review.java
  src/main/java/com/somemore/domains/review/service/DeleteReviewService.java
  src/main/java/com/somemore/domains/review/service/UpdateReviewService.java
  src/main/java/com/somemore/domains/review/service/validator/ReviewValidator.java
  src/main/java/com/somemore/domains/volunteer/validator/VolunteerDetailAccessValidatorImpl.java
  src/main/java/com/somemore/domains/volunteerapply/service/ApplyVolunteerApplyService.java
  src/main/java/com/somemore/domains/volunteerapply/service/SettleVolunteerApplyFacadeService.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeService.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyStatusChangeService.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
  src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
  src/test/java/com/somemore/domains/recruitboard/domain/RecruitBoardTest.java
  src/test/java/com/somemore/domains/recruitboard/domain/RecruitmentInfoTest.java
  src/test/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/DeleteRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/RecruitBoardDocumentServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidatorTest.java
  src/test/java/com/somemore/domains/review/domain/ReviewTest.java
  src/test/java/com/somemore/domains/review/service/validator/ReviewValidatorTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/ApproveVolunteerApplyStatusChangeServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/RejectVolunteerApplyStatusChangeServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/SettleVolunteerApplyFacadeServiceTest.java
  src/test/java/com/somemore/support/fixture/RecruitBoardFixture.java
Labels: Feature, 범수

#285 Fix/284 컴파일시 발생하는 type unchecked 경고 해결
  src/main/java/com/somemore/global/aspect/log/utils/SensitiveDataMasker.java
Labels: 서진, Fix

#280 [FEATURE] 특정 모집글 봉사자 지원 조회 필드 추가
  src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiController.java
  src/main/java/com/somemore/domains/volunteerapply/dto/response/VolunteerApplyWithReviewStatusResponseDto.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeService.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryService.java
  src/main/java/com/somemore/domains/volunteerapply/usecase/VolunteerApplyQueryFacadeUseCase.java
  src/main/java/com/somemore/domains/volunteerapply/usecase/VolunteerApplyQueryUseCase.java
  src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryServiceTest.java
Labels: Feature, 범수

#282 [Feature] 봉사자 ID, PW 로그인 추가
  src/main/java/com/somemore/global/auth/authentication/JwtAuthenticationToken.java
  src/main/java/com/somemore/global/auth/controller/SignController.java
  src/main/java/com/somemore/global/auth/dto/SignRequestDto.java
  src/main/java/com/somemore/global/auth/idpw/filter/IdPwAuthFilter.java
  src/main/java/com/somemore/global/auth/idpw/provider/CustomAuthenticationProvider.java
  src/main/java/com/somemore/global/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/global/config/SecurityConfig.java
  src/main/java/com/somemore/user/domain/User.java
  src/main/java/com/somemore/user/dto/UserAuthInfo.java
  src/main/java/com/somemore/user/repository/user/UserRepository.java
  src/main/java/com/somemore/user/repository/user/UserRepositoryImpl.java
  src/main/java/com/somemore/user/service/UserQueryService.java
  src/main/java/com/somemore/user/usecase/UserQueryUseCase.java
  src/test/java/com/somemore/user/repository/user/UserRepositoryImplTest.java
  src/test/java/com/somemore/user/service/RegisterUserServiceTest.java
  src/test/java/com/somemore/user/service/UserQueryServiceTest.java
Labels: Feature, 재중

#290 [Fix] 유저 권한 관련 문제 해결, ID/PW sign 엔드 포인트 수정
  src/main/java/com/somemore/global/auth/controller/SignController.java
  src/main/java/com/somemore/global/auth/idpw/filter/IdPwAuthFilter.java
  src/main/java/com/somemore/user/domain/UserRole.java
Labels: bug, Fix

#286 [Feature] OAuth 로그인시 토큰 전달 방식 변경
  src/main/java/com/somemore/develop/controller/TokenGenerateMachine.java
  src/main/java/com/somemore/global/auth/controller/AuthController.java
  src/main/java/com/somemore/global/auth/controller/UserInfoQueryController.java
  src/main/java/com/somemore/global/auth/cookie/CookieService.java
  src/main/java/com/somemore/global/auth/cookie/CookieUseCase.java
  src/main/java/com/somemore/global/auth/dto/UserInfoResponseDto.java
  src/main/java/com/somemore/global/auth/idpw/filter/IdPwAuthFilter.java
  src/main/java/com/somemore/global/auth/jwt/domain/TokenType.java
  src/main/java/com/somemore/global/auth/jwt/generator/HmacJwtGenerator.java
  src/main/java/com/somemore/global/auth/jwt/refresh/manager/RedisRefreshTokenManager.java
  src/main/java/com/somemore/global/auth/jwt/refresh/manager/RefreshTokenManager.java
  src/main/java/com/somemore/global/auth/jwt/refresh/refresher/DefaultJwtRefresher.java
  src/main/java/com/somemore/global/auth/jwt/service/GenerateTokensOnLoginService.java
  src/main/java/com/somemore/global/auth/jwt/service/JwtService.java
  src/main/java/com/somemore/global/auth/jwt/usecase/GenerateTokensOnLoginUseCase.java
  src/main/java/com/somemore/global/auth/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/global/auth/usecase/AuthQueryService.java
  src/main/java/com/somemore/global/auth/usecase/AuthQueryUseCase.java
  src/main/java/com/somemore/user/repository/user/UserRepository.java
  src/main/java/com/somemore/user/repository/user/UserRepositoryImpl.java
  src/main/java/com/somemore/user/service/UserQueryService.java
  src/main/java/com/somemore/user/usecase/UserQueryUseCase.java
  src/test/java/com/somemore/domains/volunteer/service/SignOutVolunteerServiceTest.java
  src/test/java/com/somemore/global/auth/cookie/CookieServiceTest.java
  src/test/java/com/somemore/global/auth/jwt/service/JwtServiceTest.java
  src/test/java/com/somemore/user/repository/user/UserRepositoryImplTest.java
  src/test/java/com/somemore/user/service/UserQueryServiceTest.java
Labels: Feature, 재중

#292 [FEATURE] Authorization header setting
  src/main/java/com/somemore/global/config/WebConfig.java
Labels: Fix

#294 [FEATURE] 카카오 OAuth 추가
  src/main/java/com/somemore/domains/volunteer/controller/VolunteerSignController.java
  src/main/java/com/somemore/domains/volunteer/service/GenerateOAuthUrlService.java
  src/main/java/com/somemore/global/auth/oauth/config/OAuth2Config.java
  src/main/java/com/somemore/global/auth/oauth/converter/NaverOAuthResponseConverter.java
  src/main/java/com/somemore/global/auth/oauth/converter/OAuthResponseConverter.java
  src/main/java/com/somemore/global/auth/oauth/converter/OAuthResponseConverterImpl.java
  src/main/java/com/somemore/global/auth/oauth/domain/CommonOAuthInfo.java
  src/main/java/com/somemore/global/auth/oauth/domain/CustomOAuth2User.java
  src/main/java/com/somemore/global/auth/oauth/domain/OAuthProvider.java
  src/main/java/com/somemore/global/auth/oauth/dto/KakaoUserProfileResponseDto.java
  src/main/java/com/somemore/global/auth/oauth/dto/NaverUserProfileResponseDto.java
  src/main/java/com/somemore/global/auth/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/global/auth/oauth/processor/OAuthUserProcessor.java
  src/main/java/com/somemore/global/auth/oauth/processor/OAuthUserProcessorImpl.java
  src/main/java/com/somemore/global/auth/oauth/registrar/OAuthInfoRegistrarImpl.java
  src/main/java/com/somemore/global/auth/oauth/service/CustomOAuth2UserService.java
  src/main/resources/application.yml
  src/test/java/com/somemore/domains/volunteer/service/GenerateOAuthUrlServiceTest.java
  src/test/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepositoryImplTest.java
Labels: Feature

#293 Feature/287 봉사 기록 엔티티와 이벤트 기반 생성 방식 구현
  src/main/java/com/somemore/domains/interestcenter/event/converter/CreateRecruitBoardMessageConverter.java
  src/main/java/com/somemore/domains/volunteerapply/service/SettleVolunteerApplyFacadeService.java
  src/main/java/com/somemore/domains/volunteerrecord/domain/VolunteerRecord.java
  src/main/java/com/somemore/domains/volunteerrecord/event/VolunteerRecordCreateEvent.java
  src/main/java/com/somemore/domains/volunteerrecord/event/VolunteerRecordEventPublisher.java
  src/main/java/com/somemore/domains/volunteerrecord/event/convert/VolunteerRecordMessageConverter.java
  src/main/java/com/somemore/domains/volunteerrecord/event/handler/SettleVolunteerHoursHandler.java
  src/main/java/com/somemore/domains/volunteerrecord/event/handler/SettleVolunteerHoursHandlerImpl.java
  src/main/java/com/somemore/domains/volunteerrecord/event/subscriber/RedisSettleVolunteerHoursSubscriber.java
  src/main/java/com/somemore/domains/volunteerrecord/repository/VolunteerRecordJpaRepository.java
  src/main/java/com/somemore/domains/volunteerrecord/repository/VolunteerRecordRepository.java
  src/main/java/com/somemore/domains/volunteerrecord/repository/VolunteerRecordRepositoryImpl.java
  src/main/java/com/somemore/domains/volunteerrecord/service/VolunteerRecordCreateService.java
  src/main/java/com/somemore/domains/volunteerrecord/usecase/VolunteerRecordCreateUseCase.java
  src/main/java/com/somemore/global/common/event/DomainEventSubType.java
  src/main/java/com/somemore/global/redis/registrar/RedisListenerRegistrar.java
  src/test/java/com/somemore/domains/volunteerrecord/domain/VolunteerRecordTest.java
  src/test/java/com/somemore/domains/volunteerrecord/service/VolunteerRecordCreateServiceTest.java
Labels: Feature, 서진

#301 [FIX] @Lob 사용시 DB에 tinytext 저장되는 문제 해결
  src/main/java/com/somemore/domains/center/domain/Center.java
  src/main/java/com/somemore/domains/community/domain/CommunityBoard.java
  src/main/java/com/somemore/domains/community/domain/CommunityComment.java
  src/main/java/com/somemore/domains/note/domain/Note.java
  src/main/java/com/somemore/domains/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/domains/review/domain/Review.java
  src/main/java/com/somemore/domains/volunteer/domain/Volunteer.java
  src/main/resources/application.yml
Labels: 범수, Fix

#299 [FIX] jpa open in view
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 범수, Fix

#297 [FEATURE] 모집글 스케쥴링
  build.gradle
  src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiController.java
  src/main/java/com/somemore/domains/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardUpdateRequestDto.java
  src/main/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepository.java
  src/main/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/main/java/com/somemore/domains/recruitboard/scheduler/RecruitBoardStatusUpdateScheduler.java
  src/main/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidator.java
  src/main/java/com/somemore/domains/recruitboard/usecase/UpdateRecruitBoardUseCase.java
  src/main/java/com/somemore/domains/volunteerapply/service/ApplyVolunteerApplyService.java
  src/main/java/com/somemore/global/config/TimeConfig.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
  src/test/java/com/somemore/domains/recruitboard/domain/RecruitBoardTest.java
  src/test/java/com/somemore/domains/recruitboard/domain/RecruitmentInfoTest.java
  src/test/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImplTest.java
  src/test/java/com/somemore/domains/recruitboard/scheduler/RecruitBoardStatusUpdateSchedulerTest.java
  src/test/java/com/somemore/domains/recruitboard/service/DeleteRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidatorTest.java
  src/test/java/com/somemore/support/fixture/RecruitBoardFixture.java
Labels: Feature, 범수

#305 [CICD] 카카오 CICD 문제 해결
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  src/main/java/com/somemore/domains/center/domain/Center.java
  src/main/java/com/somemore/domains/center/domain/PreferItem.java
  src/main/java/com/somemore/domains/volunteer/domain/Volunteer.java
  src/main/java/com/somemore/domains/volunteer/domain/VolunteerDetail.java
Labels: CICD

#309 [FEATURE] 액세스 토큰 클레임 추가 (역할 아이디)
  src/main/java/com/somemore/center/service/NEWCenterQueryService.java
  src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
  src/main/java/com/somemore/global/auth/annotation/RoleId.java
  src/main/java/com/somemore/global/auth/annotation/RoleIdArgumentResolver.java
  src/main/java/com/somemore/global/auth/annotation/UserId.java
  src/main/java/com/somemore/global/auth/annotation/UserIdArgumentResolver.java
  src/main/java/com/somemore/global/auth/authentication/JwtAuthenticationToken.java
  src/main/java/com/somemore/global/auth/authentication/UserIdentity.java
  src/main/java/com/somemore/global/auth/idpw/filter/IdPwAuthFilter.java
  src/main/java/com/somemore/global/auth/idpw/provider/CustomAuthenticationProvider.java
  src/main/java/com/somemore/global/auth/jwt/filter/JwtAuthFilter.java
  src/main/java/com/somemore/global/auth/jwt/generator/HmacJwtGenerator.java
  src/main/java/com/somemore/global/auth/jwt/generator/JwtGenerator.java
  src/main/java/com/somemore/global/auth/jwt/refresher/DefaultJwtRefresher.java
  src/main/java/com/somemore/global/auth/jwt/service/GenerateTokensOnLoginService.java
  src/main/java/com/somemore/global/auth/jwt/service/JwtService.java
  src/main/java/com/somemore/global/auth/jwt/usecase/GenerateTokensOnLoginUseCase.java
  src/main/java/com/somemore/global/auth/jwt/usecase/JwtUseCase.java
  src/main/java/com/somemore/global/auth/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/somemore/global/auth/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/somemore/global/config/WebConfig.java
  src/main/java/com/somemore/global/exception/ExceptionMessage.java
  src/main/java/com/somemore/global/exception/InvalidAuthenticationException.java
  src/main/java/com/somemore/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/somemore/volunteer/service/NEWVolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/NEWVolunteerQueryUseCase.java
  src/test/java/com/somemore/center/service/NEWCenterQueryServiceTest.java
  src/test/java/com/somemore/global/auth/jwt/service/JwtServiceTest.java
  src/test/java/com/somemore/global/auth/sign/SignOutVolunteerServiceTest.java
  src/test/java/com/somemore/volunteer/service/NEWVolunteerQueryServiceTest.java
Labels: Feature, 재중

#315 [FIX] @CurrentUser를 @UserId로 변경
  src/main/java/com/somemore/global/auth/jwt/controller/TokenExchangeController.java
  src/main/java/com/somemore/global/auth/sign/out/SignOutController.java
  src/main/java/com/somemore/global/sse/controller/SseController.java
Labels: bug, 재중, Fix

#317 [REFACTOR] 테이블 수정에 따른 모집글 리팩토링
  src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiController.java
  src/main/java/com/somemore/domains/recruitboard/domain/RecruitBoard.java
  src/main/java/com/somemore/domains/recruitboard/dto/request/RecruitBoardCreateRequestDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardDetailResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardWithCenterResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardWithLocationResponseDto.java
  src/main/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImpl.java
  src/main/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryService.java
  src/main/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardService.java
  src/main/java/com/somemore/domains/recruitboard/usecase/CreateRecruitBoardUseCase.java
  src/main/java/com/somemore/domains/recruitboard/usecase/UpdateRecruitBoardUseCase.java
  src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardCommandApiControllerTest.java
  src/test/java/com/somemore/domains/recruitboard/domain/RecruitBoardTest.java
  src/test/java/com/somemore/domains/recruitboard/repository/RecruitBoardRepositoryImplTest.java
  src/test/java/com/somemore/domains/recruitboard/scheduler/RecruitBoardStatusUpdateSchedulerTest.java
  src/test/java/com/somemore/domains/recruitboard/service/CreateRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/DeleteRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/RecruitBoardQueryServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/UpdateRecruitBoardServiceTest.java
  src/test/java/com/somemore/domains/recruitboard/service/validator/RecruitBoardValidatorTest.java
  src/test/java/com/somemore/support/annotation/MockUser.java
  src/test/java/com/somemore/support/annotation/MockUserSecurityContextFactory.java
  src/test/java/com/somemore/support/fixture/RecruitBoardFixture.java
Labels: 범수, Refactor

#319 [FIX] 회원가입시 비밀번호 해시 처리
  src/main/java/com/somemore/global/auth/annotation/RoleId.java
  src/main/java/com/somemore/global/auth/annotation/UserId.java
  src/main/java/com/somemore/global/auth/idpw/provider/CustomAuthenticationProvider.java
  src/main/java/com/somemore/global/util/encoder/BCryptPasswordEncoderUtil.java
  src/main/java/com/somemore/user/dto/UserAuthInfo.java
  src/test/java/com/somemore/global/util/encoder/BCryptPasswordEncoderUtilTest.java
Labels: bug, 재중, Fix

#322 [REFACTOR] 새로운 테이블에 따른 봉사지원 리팩토링
  src/main/java/com/somemore/domains/volunteerapply/controller/CenterVolunteerApplyCommandApiController.java
  src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyCommandApiController.java
  src/main/java/com/somemore/domains/volunteerapply/service/SettleVolunteerApplyFacadeService.java
  src/main/java/com/somemore/volunteer/domain/NEWVolunteer.java
  src/main/java/com/somemore/volunteer/service/UpdateVolunteerLockService.java
  src/main/java/com/somemore/volunteer/usecase/UpdateVolunteerUseCase.java
  src/test/java/com/somemore/domains/volunteer/service/UpdateVolunteerLockServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/controller/CenterVolunteerApplyCommandApiControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyCommandApiControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/ApplyVolunteerApplyStatusChangeServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/SettleVolunteerApplyFacadeServiceTest.java
  src/test/java/com/somemore/volunteer/domain/NEWVolunteerTest.java
  src/test/java/com/somemore/volunteer/service/UpdateVolunteerLockServiceTest.java
Labels: 범수, Refactor

#325 [FEATURE] 모집글 본인이 작성한 게시글 조회 기능 추가
  src/main/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiController.java
  src/main/java/com/somemore/domains/recruitboard/dto/response/RecruitBoardResponseDto.java
  src/test/java/com/somemore/domains/recruitboard/controller/RecruitBoardQueryApiControllerTest.java
Labels: Feature, 범수

#326 Feature/288 presigned 이미지 업로드 방식 구현
  src/main/java/com/somemore/global/imageupload/service/ImageUploadService.java
  src/main/java/com/somemore/global/imageupload/usecase/ImageUploadUseCase.java
  src/main/java/com/somemore/global/imageupload/util/ImageUploadUtils.java
  src/main/java/com/somemore/global/imageupload/validator/DefaultImageUploadValidator.java
  src/main/java/com/somemore/global/imageupload/validator/ImageUploadValidator.java
  src/test/java/com/somemore/global/imageupload/service/ImageUploadServiceTest.java
  src/test/java/com/somemore/global/imageupload/validator/DefaultImageUploadValidatorTest.java
Labels: Feature, 서진

#330 [FIX] 봉사자 특정 모집글 지원 상태 조회 API 수정
  src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiController.java
  src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
Labels: bug, 범수, Fix

#332 [FEATURE] OAuth 로그인 중, 신규 유저의 봉사자 등록 로직 추가
  src/main/java/com/somemore/global/auth/oauth/processor/OAuthUserProcessorImpl.java
  src/main/java/com/somemore/global/auth/sign/up/SignUpController.java
  src/main/java/com/somemore/global/auth/sign/up/SignUpService.java
  src/main/java/com/somemore/global/auth/sign/up/SignUpUseCase.java
Labels: Feature

#333 [FEAT] 유저 기본 정보 입력 상태 확인 API 추가
  src/main/java/com/somemore/user/controller/UserQueryController.java
  src/main/java/com/somemore/user/service/ValidateBasicInfoService.java
Labels: Feature, 재중

#336 fix/327 랭킹 json 직렬화 문제 해결
  src/main/java/com/somemore/domains/volunteerrecord/repository/VolunteerRankingRedisRepository.java
  src/main/java/com/somemore/global/redis/config/RedisConfig.java
  src/test/java/com/somemore/domains/volunteerrecord/service/GetVolunteerRankingServiceTest.java
  src/test/java/com/somemore/domains/volunteerrecord/service/RankingCacheServiceTest.java
Labels: 서진, Fix

#334 [REFACTOR] 리뷰 커맨드 기능 리팩토링
  src/main/java/com/somemore/domains/review/controller/ReviewCommandApiController.java
  src/main/java/com/somemore/domains/review/domain/Review.java
  src/main/java/com/somemore/domains/review/dto/request/ReviewCreateRequestDto.java
  src/main/java/com/somemore/domains/review/dto/response/ReviewDetailResponseDto.java
  src/main/java/com/somemore/domains/review/dto/response/ReviewDetailWithNicknameResponseDto.java
  src/main/java/com/somemore/domains/review/service/CreateReviewService.java
  src/main/java/com/somemore/domains/review/service/UpdateReviewService.java
  src/main/java/com/somemore/domains/review/usecase/CreateReviewUseCase.java
  src/main/java/com/somemore/domains/review/usecase/UpdateReviewUseCase.java
  src/test/java/com/somemore/domains/review/controller/ReviewCommandApiControllerTest.java
  src/test/java/com/somemore/domains/review/domain/ReviewTest.java
  src/test/java/com/somemore/domains/review/repository/ReviewRepositoryImplTest.java
  src/test/java/com/somemore/domains/review/service/CreateReviewServiceTest.java
  src/test/java/com/somemore/domains/review/service/DeleteReviewServiceTest.java
  src/test/java/com/somemore/domains/review/service/ReviewQueryServiceTest.java
  src/test/java/com/somemore/domains/review/service/UpdateReviewServiceTest.java
  src/test/java/com/somemore/domains/review/service/validator/ReviewValidatorTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeServiceTest.java
Labels: Refactor

#338 Refactor/320 기관 프로필 조회 리팩토링
  src/main/java/com/somemore/center/controller/CenterQueryApiController.java
  src/main/java/com/somemore/center/dto/response/CenterProfileResponseDto.java
  src/main/java/com/somemore/center/repository/NEWCenterRepository.java
  src/main/java/com/somemore/center/repository/NEWCenterRepositoryImpl.java
  src/main/java/com/somemore/center/repository/record/CenterProfileDto.java
  src/main/java/com/somemore/center/service/NEWCenterQueryService.java
  src/main/java/com/somemore/center/usecase/NEWCenterQueryUseCase.java
  src/main/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepository.java
  src/main/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepositoryImpl.java
  src/main/java/com/somemore/user/repository/usercommonattribute/record/UserProfileDto.java
  src/main/java/com/somemore/user/service/UserQueryService.java
  src/main/java/com/somemore/user/usecase/UserQueryUseCase.java
  src/test/java/com/somemore/center/controller/CenterQueryApiControllerTest.java
  src/test/java/com/somemore/center/repository/NEWCenterRepositoryImplTest.java
  src/test/java/com/somemore/center/service/NEWCenterQueryServiceTest.java
  src/test/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepositoryImplTest.java
  src/test/java/com/somemore/user/service/UserQueryServiceTest.java
Labels: 서진, Refactor

#340 [FEATURE] 유저 프로필(기본정보) 수정
  src/main/java/com/somemore/center/domain/NEWCenter.java
  src/main/java/com/somemore/user/controller/UserCommandController.java
  src/main/java/com/somemore/user/controller/UserQueryController.java
  src/main/java/com/somemore/user/domain/UserCommonAttribute.java
  src/main/java/com/somemore/user/dto/basicinfo/CenterBasicInfoRequestDto.java
  src/main/java/com/somemore/user/dto/basicinfo/CommonBasicInfoRequestDto.java
  src/main/java/com/somemore/user/dto/basicinfo/VolunteerBasicInfoRequestDto.java
  src/main/java/com/somemore/user/service/UpdateBasicInfoService.java
  src/main/java/com/somemore/user/usecase/UpdateBasicInfoUseCase.java
  src/main/java/com/somemore/volunteer/domain/NEWVolunteer.java
  src/test/java/com/somemore/user/service/UpdateBasicInfoServiceTest.java
  src/test/java/com/somemore/user/service/ValidateBasicInfoServiceTest.java
Labels: Feature, 재중

#343 [FIX] git actions 버전 문제 해결
  .github/workflows/CI.yml
Labels: Fix

#337 [REFACTOR] 봉사 지원 조회 관련 리팩토링
  src/main/java/com/somemore/domains/volunteer/dto/response/VolunteerSimpleInfoResponseDto.java
  src/main/java/com/somemore/domains/volunteer/repository/VolunteerRepository.java
  src/main/java/com/somemore/domains/volunteer/repository/VolunteerRepositoryImpl.java
  src/main/java/com/somemore/domains/volunteer/repository/mapper/VolunteerSimpleInfo.java
  src/main/java/com/somemore/domains/volunteer/service/VolunteerQueryService.java
  src/main/java/com/somemore/domains/volunteer/usecase/VolunteerQueryUseCase.java
  src/main/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiController.java
  src/main/java/com/somemore/domains/volunteerapply/dto/response/VolunteerApplyVolunteerInfoResponseDto.java
  src/main/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepository.java
  src/main/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeService.java
  src/main/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepository.java
  src/main/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepositoryImpl.java
  src/main/java/com/somemore/user/service/UserQueryService.java
  src/main/java/com/somemore/user/usecase/UserQueryUseCase.java
  src/main/java/com/somemore/volunteer/dto/VolunteerInfoResponseDto.java
  src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepository.java
  src/main/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImpl.java
  src/main/java/com/somemore/volunteer/repository/record/VolunteerNicknameAndId.java
  src/main/java/com/somemore/volunteer/service/NEWVolunteerQueryService.java
  src/main/java/com/somemore/volunteer/usecase/NEWVolunteerQueryUseCase.java
  src/test/java/com/somemore/domains/volunteer/repository/VolunteerRepositoryImplTest.java
  src/test/java/com/somemore/domains/volunteer/service/VolunteerQueryServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/controller/VolunteerApplyQueryApiControllerTest.java
  src/test/java/com/somemore/domains/volunteerapply/repository/VolunteerApplyRepositoryImplTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/ApplyVolunteerApplyStatusChangeServiceTest.java
  src/test/java/com/somemore/domains/volunteerapply/service/VolunteerApplyQueryFacadeServiceTest.java
  src/test/java/com/somemore/user/repository/usercommonattribute/UserCommonAttributeRepositoryImplTest.java
  src/test/java/com/somemore/user/service/UserQueryServiceTest.java
  src/test/java/com/somemore/volunteer/repository/NEWVolunteerRepositoryImplTest.java
  src/test/java/com/somemore/volunteer/service/NEWVolunteerQueryServiceTest.java
Labels: 범수, Refactor
